=== IRC log 2012-04-04

****
* Source: https://gnusha.org/bitcoin-core-dev/bitcoin-dev-2010-2015.txt.xz
* Author: Wumpus (among others)
* Date copied: 2022-05-18
****

....
1333560356|1|wumpus|for errors that are fatal or really require the users long term attention
1333560364|1|BlueMatt|heh, yet another request for sending double spend notifications...
1333560366|1|BlueMatt|wow...
1333560405|1|gavinandresen|while we're cleaning up code... wxAnything aught to be renamed
1333560413|1|jgarzik|heh
1333560441|1|wumpus|gavinandresen: yes
1333560554|1|lh77|What is mintchip?
1333560562|1|dvide|the best ice cream flavour
1333560565|128|erle-|Quit: erle-
1333560581|1|Graet|its the evolution of currency.
1333560588|1|BlueMatt|heh
1333560590|1|Graet|http://mintchipchallenge.com/
1333560592|1|Graet|:P
1333560598|1|lh77|is it like bitcoin?
1333560600|1|lh77|peer to peer?
1333560604|1|Graet|not at all
1333560612|1|lh77|what does it do exactly?
1333560615|1|Graet|mint = canadian mint
1333560620|1|Graet|read link?
1333560626|1|Graet|i'm going bed :)
1333560638|32|Joric_|#bitcoin-dev
1333560638|128|Joric_|Changing host
1333560638|32|Joric_|#bitcoin-dev
1333560702|128|coingenuity|Read error: Connection reset by peer
1333560710|1|freewil|well one thing mintchip has that bitcoin doesnt is a large organization behind it
1333560724|128|Joric|Ping timeout: 246 seconds
1333560740|1|Diablo-D3|no one has even proven its from the canadian mint
1333560741|1|Diablo-D3|also
1333560745|1|Diablo-D3|its not distributed nor secure
1333560760|1|Diablo-D3|its DRMed virtual money using a central source to issue keys
1333560762|1|BlueMatt|wait, do I agree with Diablo-D3 for once?
1333560776|1|wumpus|that bitcoin has no large organization behind it is a good thing imo
1333560776|1|BlueMatt|damn im getting cynical
1333560783|128|barmstro_|Remote host closed the connection
1333560813|1|Blitzboom|no it’s not
1333560819|1|gavinandresen|awww.... we don't get no respect, BTC isn't one of the currency codes supported by MintChip
1333560820|8|Joric_|Joric
1333560833|1|Blitzboom|it would be good to have funding for developmenta, PR and legal matters
1333560844|1|wumpus|bitcoin is neutral, which is a good thing, and the only way it can work
1333560863|1|gavinandresen|PR is lovebitcoins.org
1333560866|1|wumpus|if it was controlled by an organisation it'd just be another virtual object type
1333560874|1|wumpus|and I would have zero interest in it
1333560893|1|freewil|im just talking about a non-profit to fund development
1333560901|1|gavinandresen|I'm talking with somebody tomorrow about a non-profit for legal stuff about bitcoin
1333560925|1|freewil|gavinandresen, what about paying you to develop full time :)
1333560942|1|wumpus|that's good, as long as it doesn't become a central point of failure
1333560948|1|BlueMatt|gavinandresen pretty much does develop full-time
1333560954|1|gavinandresen|freewil: feel free.  TruCoin was paying me until their funding dried up...
1333560955|1|BlueMatt|(and we should pay him)
1333561003|1|gavinandresen|There are several workable models for funding open source projects, if I was more of a business person I'd spend more time thinking about which one makes sense for bitcoin
1333561040|1|freewil|the only ones i really know are donations and support-based revenue
1333561051|1|Blitzboom|satoshi should simply throw in a few hundred k BTC
1333561069|1|gavinandresen|throw in... where ?
1333561080|1|Graet|the "kitty"
1333561081|1|wumpus|in gavinandresens account
1333561094|1|Blitzboom|that non-profit’s bank
1333561140|128|Diapolo|Quit: Page closed
1333561143|1|Blitzboom|yeah, donations should work. there are plenty of large holders who have a healthy interest in it
1333561183|1|BlueMatt|luckily we are a "currency"
1333561192|1|BlueMatt|getting eg mtgox to donate a bit wouldnt be hard
1333561243|1|denisx|isnt deepbit the biggest profitmaker?
1333561248|1|wumpus|support-based sounds interesting, maybe we should add a payment to open issues :-)
1333561258|128|mmoya|Ping timeout: 244 seconds
1333561281|1|Joric|what do you think about blocking mtgox accounts due to 'tainted' coins? that bitcoin AIDS is making me nervous
1333561300|1|BlueMatt|Joric: welcome to the world of finance regulation
1333561306|32|[Tycho]|#bitcoin-dev
1333561321|1|wumpus|well mtgox can decide what they do for themselves right?
1333561340|1|Joric|it's the biggest exchange atm
1333561356|1|Joric|most coins end there
1333561389|1|BlueMatt|wumpus: sort of, though bitcoin isnt technically regulated as a currency, they still have to try to regulate it as if it were to avoid aml issues
1333561421|1|wumpus|BlueMatt: yes, that's the problem with it being so easy to trace
1333561455|1|jgarzik|bitcoin AIDS?
1333561464|1|wumpus|though a global ledger is probably the only way a distributed currency can work
1333561477|1|jgarzik|does mtgox have a list of tainted coins?
1333561482|1|wumpus|yes
1333561491|1|wumpus|they have a naughty list
1333561502|32|barmstrong|#bitcoin-dev
1333561588|1|wumpus|I think the bigger problem is not mtgox specifically but that bitcoin is so dependent on a few exchanges, they are centralized bottlenecks
....
