=== David Harding - Harmony and Discord

****
* Source: https://bitcointalk.org/dec/p1.html
* Author: David Harding
* Date copied: 2022-05-25
****

*Harmony and Discord*

Bitcoin experts talk often of _consensus_, whose meaning is
abstract and 
hard to pin down. But the word consensus evolved from the Latin word 
_concentus_, "a singing together, harmony,"[1] so
let us talk not of 
Bitcoin consensus but of Bitcoin harmony. 
 
Harmony is what makes Bitcoin work. Thousands of full nodes each work 
independently to verify the transactions they receive are valid, 
producing a harmonious agreement about the state of the Bitcoin 
ledger without any node operator needing to trust anyone else. It's 
similar to a chorus where each member sings the same song at the same 
time to produce something far more beautiful than any of them could 
produce alone. 
 
The result of Bitcoin harmony is a system where bitcoins are safe not 
just from petty thieves (provided you keep your keys secure) but also 
from endless inflation, mass or targeted confiscation, or simply the 
bureaucratic morass that is the legacy financial system. 
 
*Discord*
 
Discord is the enemy of harmony. If, in the great chorus of Bitcoin
full 
nodes, half the singers decided to suddenly switch tunes, the harmony 
would be lost. In its place would be two smaller singing groups who
try 
to out sing each other (or who may compete through less scrupulous
means), 
leaving everyone worse off. 
 
This is what a contentious hard fork has the potential to do.  Some 
people will program their full nodes to sing one song; other people
will 
program their full nodes to sing a different song.  In the cacophony 
that results, there will surely be confusion, recriminations, and loss 
of confidence. 
 
For this reason, contentious hard forks are to be avoided. 
 
But this doesn't mean we have to sing the same song forever. We have 
other options. The first is gathering widespread agreement to change
to 
a new song---to hard fork the system without giving discord a
foothold. 
 
The second way is to add new layers to the existing harmony.  A chorus 
will often sing accompaniment to an orchestra, and together they can 
entertain audiences neither of them could have pleased alone.  Soft
forks 
are the preferred method for adding new features to Bitcoin because
they 
allow old nodes to continue to sing the same old song (unless they're 
miners), while new nodes get to partake in the expanded choices. 
 
Given two forking paths to the same feature, a soft fork is the safer 
option because it leaves no room for discord, and no risk that the 
essential harmony that underlies Bitcoin's security will be lost.

'''''

[1] Cassell's Latin Dictionary, Wiley Publishing, fifth ed.
