== About btcphilosophy

This project is meant as a guide for new developers in Bitcoin to
learn about this new digital currency's fundamental properties and how
seasoned Bitcoin developers think about them.

image::under-construction.svg[width=20%,float="right",align="center"]

WARNING: This repo is heavily under construction. If this sign is
still here on 2022-06-01 (CEST), we have abandoned this
project. Sorry.

=== Intended reader

The typical reader is a developer who just started digging into
Bitcoin development or have worked in the Bitcoin space in one form or
the other for a while.

The reader doesn't have to know every ins an outs of Bitcoin, but
should understand how it operates on a high level. For example, the
following should be clear to the reader beforehand:

* What proof-of-work is
* How blocks are interconnected
* That transactions are usually signed using private keys before being
  published to the Bitcoin peer-to-peer network.

The reader should also be humble and willing to re-evaluate his/her
opinions. The materials we present here are written by people who have
been studying Bitcoin for a very long time and some were into digital
money way before Bitcoin existed (yes, they existed before Bitcoin).

=== How is this organized?

The project is sectioned into topics. Each topic will guide you
through a number of links to articles or videos, that we recommend
reading and we briefly discuss each link.

The links refer to external resources on platforms we can't
control. We have therefore saved the linked articles locally in this
repository, along with info on where it was copied from, and when.

=== What to expect

There are lots and lots of people involved in Bitcoin and they
sometimes have opposing opinions on some topics, so some resources may
appear contradictory others. However, we will mostly try to stick to
the facts, where opinions don't matter.

This guide should help the reader to more quickly get up to speed on basic
Bitcoin developer philosophy. After reading this collection of
articles, you'll

* have leapfrogged more than a decade of Bitcoin experience
* be able to distinguish useful Bitcoin ideas from, well, less useful ideas
* get accustomed to some great places for Bitcoin information
* be humbled by the vast amount of wisdom available
* be humbled by the breadth of this field

=== Who wrote this?

The main authors are Kalle Rosenbaum and Linnéa Rosenbaum. This work
is commissioned and funded by Chaincode Labs. Chaincode Labs run
internships for developers where the attendants learn about Bitcoin
development.
