== About btcphilosophy

This project is a guide for new developers in Bitcoin to learn about
the digital currency's fundamental properties and how seasoned Bitcoin
developers think about them.

This guide should help the reader to get up to speed on basic Bitcoin developer
philosophy. After reading this collection of articles, you'll:

* have cruised over a decade of Bitcoin experience
* be able to distinguish useful Bitcoin ideas from, well, less useful ideas
* get accustomed to some great places for Bitcoin information
* be humbled by the vast amount of wisdom available
* be humbled by the breadth of this field

image::under-construction.svg[width=20%,float="right",align="center"]

WARNING: This repo is heavily under construction. If this sign is
still here on 2022-06-01 (CEST), we have abandoned this
project. Sorry.

=== Intended reader

The typical reader is a developer who just started digging into
Bitcoin development or has worked in the Bitcoin space in one form or
the other.

The reader doesn't have to know all the ins and outs of Bitcoin, but
should understand how it operates on a high level. For example, the
following should be clear to the reader beforehand:

* What proof-of-work is
* How blocks are interconnected
* Lifecycle of transactions

=== How is this organized?

The project is sectioned into topics. Each topic will guide you
through a number of links to articles or videos, that we recommend
reading and briefly discuss each link. The material presented is
written by individuals who have studied Bitcoin for a long time.

The links refer to external resources on platforms we can't
control. We have therefore saved the linked articles locally in this
repository, along with info on where it was copied from, and when. The
resources are collected in an appendix grouped by the chapter they are
linked from.

The links throughout the chapters refer to the original sources, but
if you don't have an internet connection, the links appear dead, or
the content seems severely changed, you can read the content from the
appendix.

=== What to expect

There are lots people involved in Bitcoin; some have opposing opinions and so
certain resources may appear contradictory to one another. However, we will
attempt to stick to the facts, where opinions do not matter.

Topics cannot be fully separated from others; overlaps do exist. For example,
fungibility is briefly discussed in the privacy chapter, even though
there is a separate chapter for fungibility.

=== Who wrote this?

The main authors are Kalle Rosenbaum and Linnéa Rosenbaum. This work
is commissioned and funded by Chaincode Labs. Chaincode Labs runs internships
for developers where the attendants learn about Bitcoin development.
