= Note to reviewers

Thank you so much for reviewing this work. The things we're most
interested in are:

* Factual errors
* Severe omissions
* Language (We're Swedes, any help here is useful)
* Structural improvements

Other kinds of input is of course helpful too, we do want that, but we
might not handle it promptly due to time restrictions.

To get on the same page regarding intended audience and what to expect
from this work, it'd help if you, before reviewing the book, read the
first few sections of link:readme.adoc[readme.adoc] up to (and
excluding) the "`Build`" section.

We prefer to receive the feedback as Github issues or even better as
pull requests, but any means will do.

[qrcode,role=qrcode]
----
https://example.com/757ce1f3
----

[qrcode,role=qrcode]
----
https://example.com/44a4c727
----

[qrcode,role=qrcode]
----
https://example.com/1baeff23
----

[qrcode,role=qrcode]
----
https://example.com/3f9aa6e4
----

[qrcode,role=qrcode]
----
https://example.com/ce706dbb
----

[qrcode,role=qrcode]
----
https://example.com/0e704448
----

[qrcode,role=qrcode]
----
https://example.com/7f9a1f0e
----

[qrcode,role=qrcode]
----
https://example.com/e850a71a
----

[qrcode,role=qrcode]
----
https://example.com/ee6ba21e
----

[qrcode,role=qrcode]
----
https://example.com/4992b2bf
----

[qrcode,role=qrcode]
----
https://example.com/ee6ba21e
----

[qrcode,role=qrcode]
----
https://example.com/0f79b795
----

[qrcode,role=qrcode]
----
https://example.com/15fd60c6
----

[qrcode,role=qrcode]
----
https://example.com/d2bc81b3
----

[qrcode,role=qrcode]
----
https://example.com/42d00df5
----

[qrcode,role=qrcode]
----
https://example.com/c8509042
----

[qrcode,role=qrcode]
----
https://example.com/6a7b0437
----

[qrcode,role=qrcode]
----
https://example.com/6c67b9a2
----

[qrcode,role=qrcode]
----
https://example.com/55a9040d
----

[qrcode,role=qrcode]
----
https://example.com/ee6ba21e
----

[qrcode,role=qrcode]
----
https://example.com/681af2d4
----

[qrcode,role=qrcode]
----
https://example.com/5088d203
----

[qrcode,role=qrcode]
----
https://example.com/a5876935
----

[qrcode,role=qrcode]
----
https://example.com/4d896c5f
----

[qrcode,role=qrcode]
----
https://example.com/a1c74ae3
----

[qrcode,role=qrcode]
----
https://example.com/a5876935
----

[qrcode,role=qrcode]
----
https://example.com/d0046310
----

[qrcode,role=qrcode]
----
https://example.com/0f1e1ede
----

[qrcode,role=qrcode]
----
https://example.com/a1c74ae3
----

[qrcode,role=qrcode]
----
https://example.com/f10ec3ff
----

[qrcode,role=qrcode]
----
https://example.com/d2bc81b3
----

[qrcode,role=qrcode]
----
https://example.com/43a6392d
----

[qrcode,role=qrcode]
----
https://example.com/94c98a92
----

[qrcode,role=qrcode]
----
https://example.com/0f79b795
----

[qrcode,role=qrcode]
----
https://example.com/2816fd91
----

[qrcode,role=qrcode]
----
https://example.com/f10ec3ff
----

[qrcode,role=qrcode]
----
https://example.com/8c8169bd
----

[qrcode,role=qrcode]
----
https://example.com/c088d37a
----

Reading can take place on https://rosenbaum.se/btcphil which we update
on every push. But if you prefer you can read it directly from source
on Github (but you won't see the images or the otherwise awesome
typesetting) or build it yourself. You can find build instructions in
link:readme.adoc[readme.adoc].

