=== Satoshi Nakamoto - Re: overflow bug SERIOUS

****
* Source: https://bitcointalk.org/index.php?topic=823.msg9531#msg9531
* Author: Satoshi Nakamoto
* Date copied: 2022-05-26
****

++++
		<table width="90%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td>
					<br />
					<hr size="2" width="100%" />
					Title: <b>overflow bug SERIOUS</b><br />
					Post by: <b>lfm</b> on <b>August 15, 2010, 07:04:11 PM</b>
					<hr />
					<div style="margin: 0 5ex;">seems a block at height 74638 has expoited a bug in the net. It uses an integer overflow to make a negative total transaction. The two transaction outputs are: <br /><br />&nbsp;out Value:92233720368.54(7ffffffffff85ee0) out Value:92233720368.54(7ff<br />ffffffff85ee0)<br /><br />We need a fix asap<br /><br />Edit: <br />(satoshi)<br />0.3.10 patch download links here:<br />http://bitcointalk.org/index.php?topic=827.0<br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 07:25:58 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Original post: http://bitcointalk.org/index.php?topic=822.0</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 08:26:44 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><del>Whether to stop generating depends on the possible solution. If there are ever bad blocks, I can imagine an officially patched Bitcoin could be hard coded to exclude bad transactions contained in the block chain so that although the bad transactions would still be sitting in the chain, they would be ignored. I recommend people keep on generating if you were previously generating but be cautious about transactions until we hear back from Satoshi.</del><br /><br />The recommendation (http://bitcointalk.org/index.php?topic=823.msg9531#msg9531) is to stop generating.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Gavin Andresen</b> on <b>August 15, 2010, 08:39:42 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Until there is a better fix... after a very small amount of testing this seems to work:<br /><div class="codeheader">Code:</div><div class="code">--- a/main.h<br />+++ b/main.h<br />@@ -473,8 +473,12 @@ public:<br />&nbsp;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;// Check for negative values<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;foreach(const CTxOut&amp; txout, vout)<br />+ {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if (txout.nValue &lt; 0)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;return error(&quot;CTransaction::CheckTransaction() : txout.nValue negative&quot;);<br />+ if (txout.nValue &gt; 21000000*COIN)<br />+ return error(&quot;CTransaction::CheckTransaction() : txout.nValue over-max&quot;);<br />+ }<br />&nbsp;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if (IsCoinBase())<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{<br />@@ -520,6 +524,8 @@ public:<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;int64 nValueOut = 0;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;foreach(const CTxOut&amp; txout, vout)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;{<br />+ if (txout.nValue &gt; 21000000*COIN)<br />+ continue; // ignore over-max-value...<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;if (txout.nValue &lt; 0)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;throw runtime_error(&quot;CTransaction::GetValueOut() : negative value&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nValueOut += txout.nValue;<br /><br /></div>You&#039;ll need to re-download the part of the block chain before the bad block-- remove the blkindex.dat and blk0001.dat files.&nbsp; &nbsp;I started with knightmb&#039;s blockchain (http://knightmb.dyndns.org/files/bitcoin/blocks/) snapshot.<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>jgarzik</b> on <b>August 15, 2010, 08:42:49 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Or the same patch from your github, http://gist.github.com/525921 (http://gist.github.com/525921) which gives us the raw patch that can be applied directly,<br />http://gist.github.com/raw/525921/fe2ad7583f0dd2444caa0b3e24d750bf45cac11b/Quick%20fix%20block%2074652 (http://gist.github.com/raw/525921/fe2ad7583f0dd2444caa0b3e24d750bf45cac11b/Quick%20fix%20block%2074652)<br /><br /><b>EDIT</b>:&nbsp; I was unable to patch directly using this, perhaps CRLF problems.<br /><br />I applied your changes manually, and uploaded the result here: http://yyz.us/bitcoin/patch.bitcoin-gavin-overflow-quick-fix (http://yyz.us/bitcoin/patch.bitcoin-gavin-overflow-quick-fix)<br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 08:59:09 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Here&#039;s the preliminary change.&nbsp; Look right?&nbsp; I have more changes to make, this isn&#039;t all of it.&nbsp; Will SVN shortly.<br /><br /><div class="codeheader">Code:</div><div class="code">&nbsp; &nbsp; bool CheckTransaction() const<br />&nbsp; &nbsp; {<br />&nbsp; &nbsp; &nbsp; &nbsp; // Basic checks that don&#039;t depend on any context<br />&nbsp; &nbsp; &nbsp; &nbsp; if (vin.empty() || vout.empty())<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : vin or vout empty&quot;);<br /><br />&nbsp; &nbsp; &nbsp; &nbsp; // Check for negative and overflow values<br />&nbsp; &nbsp; &nbsp; &nbsp; int64 nTotal = 0;<br />&nbsp; &nbsp; &nbsp; &nbsp; foreach(const CTxOut&amp; txout, vout)<br />&nbsp; &nbsp; &nbsp; &nbsp; {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (txout.nValue &lt; 0)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : txout.nValue negative&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (txout.nValue &gt; 21000000 * COIN)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : txout.nValue too high&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nTotal += txout.nValue;<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (nTotal &gt; 21000000 * COIN)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : txout total too high&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; }<br /><br />&nbsp; &nbsp; &nbsp; &nbsp; if (IsCoinBase())<br />&nbsp; &nbsp; &nbsp; &nbsp; {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (vin[0].scriptSig.size() &lt; 2 || vin[0].scriptSig.size() &gt; 100)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : coinbase script size&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; }<br />&nbsp; &nbsp; &nbsp; &nbsp; else<br />&nbsp; &nbsp; &nbsp; &nbsp; {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; foreach(const CTxIn&amp; txin, vin)<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (txin.prevout.IsNull())<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return error(&quot;CTransaction::CheckTransaction() : prevout is null&quot;);<br />&nbsp; &nbsp; &nbsp; &nbsp; }<br /><br />&nbsp; &nbsp; &nbsp; &nbsp; return true;<br />&nbsp; &nbsp; }<br /></div><br />Don&#039;t sticky the topic, nobody looks up there.&nbsp; There&#039;ll be enough posts to bump.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 09:06:45 PM</b>
					<hr />
					<div style="margin: 0 5ex;">It would help if people stop generating.&nbsp; We will probably need to re-do a branch around the current one, and the less you generate the faster that will be.<br /><br />A first patch will be in SVN rev 132.&nbsp; It&#039;s not uploaded yet.&nbsp; I&#039;m pushing some other misc changes out of the way first, then I&#039;ll upload the patch for this.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 09:09:53 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I&#039;m afraid the community is just too big and distributed now to expect much in the way of voluntary quick action on anything, especially generation which I&#039;m sure many have on automatic and largely unmoderated.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Gavin Andresen</b> on <b>August 15, 2010, 09:10:33 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Looks good to me.<br /><br />Can you easily hardcode a check for the bad block&#039;s hash at startup and orphan it and subsequent blocks if they&#039;re on the best-block chain?<br />It&#039;s painful to have to re-download all or most of the chain to fix this...<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 09:15:18 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9534#msg9534">Quote from: gavinandresen on August 15, 2010, 09:10:33 PM</a></div><div class="quote">Looks good to me.<br /><br />Can you easily hardcode a check for the bad block&#039;s hash at startup and orphan it and subsequent blocks if they&#039;re on the best-block chain?<br />It&#039;s painful to have to re-download all or most of the chain to fix this...</div>Or just a quick re-verification of all blocks. After all, it is 5x faster (http://bitcointalk.org/index.php?topic=550.0) than it used t be. ;)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 09:23:55 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Once you have an update, you could download knightmb&#039;s block chain. &nbsp;You&#039;ll want one that&#039;s old enough that it ends <i>before</i> block 74000 so the most recent security lockin will check it. &nbsp;Can someone find the link for that?&nbsp; </div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>theymos</b> on <b>August 15, 2010, 09:26:09 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9539#msg9539">Quote from: satoshi on August 15, 2010, 09:23:55 PM</a></div><div class="quote">Once you have an update, you could download knightmb&#039;s block chain. &nbsp;You&#039;ll want one that&#039;s old enough that it ends <i>before</i> block 74000 so the most recent security lockin will check it. &nbsp;Can someone find the link for that?&nbsp; <br /></div><br />http://knightmb.dyndns.org/files/bitcoin/blocks/</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 09:29:08 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I prefer to just re-download them.<br /><br />Block verification after the patch but before everyone upgrades is going to be SLOW! It&#039;ll probably cause the next difficulty adjustment to decrease significantly. Of course everyone will probably have upgraded by the time the next adjustment rolls around, so we&#039;ll probably roll through it relatively quickly.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 09:36:30 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Edit: Hmm, I see there is an info file included which might just clue me in.<br /><br />How about explaining to us stupid newbies what we would do with the blockchain once we download it?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>jgarzik</b> on <b>August 15, 2010, 09:38:41 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9545#msg9545">Quote from: kencausey on August 15, 2010, 09:36:30 PM</a></div><div class="quote">How about explaining to us stupid newbies what we would do with the blockchain once we download it?<br /></div><br />It means replacing files in the bitcoin data directory.&nbsp; It is not recommended, unless you know what you&#039;re doing.<br /><br />Easiest and safest way is to backup wallet.dat then redownload everything.<br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 09:40:19 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Patch is uploaded to SVN rev 132! <br /><br />For now, recommended steps:<br />1) Shut down.<br />2) Download knightmb&#039;s blk files.&nbsp; (replace your blk0001.dat and blkindex.dat files)<br />3) Upgrade.<br />4) It should start out with less than 74000 blocks. Let it redownload the rest.<br /><br />If you don&#039;t want to use knightmb&#039;s files, you could just delete your blk*.dat files, but it&#039;s going to be a lot of load on the network if everyone is downloading the whole block index at once.<br /><br />I&#039;ll build releases shortly. </div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 09:40:31 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9545#msg9545">Quote from: kencausey on August 15, 2010, 09:36:30 PM</a></div><div class="quote">How about explaining to us stupid newbies what we would do with the blockchain once we download it?<br /></div>While Bitcoin is not running, you put it in your Bitcoin data directory. ~/.bitcoin on Linux. If you want to re-download the whole chain, you just delete the file from the data directory while Bitcoin is not running.<br /><br />I&#039;m going to be move my blk00x.dat files and blkindex.dat file out of by data directory and restart the client. Those are the correct files, right?<br /><br />Edit: I&#039;ll also backup the whole directory, like I usually do before upgrades.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>jgarzik</b> on <b>August 15, 2010, 09:50:57 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9548#msg9548">Quote from: satoshi on August 15, 2010, 09:40:19 PM</a></div><div class="quote">If you don&#039;t want to use knightmb&#039;s files, you could just delete your blk*.dat files, but it&#039;s going to be a lot of load on the network if everyone is downloading the whole block index at once.<br /></div><br />Anybody wanna volunteer to create blk*.dat for block chain &lt;= 64637 ?<br /><br />Maybe the official binaries could simply ship a known-good block chain, to save time and bandwidth?<br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 10:05:11 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Will the bug fix include the 4-way SSE2 patch (http://bitcointalk.org/index.php?topic=820.msg9452#msg9452) of 0.3.9 rc2? Thanks for letting me know that it is included (http://bitcointalk.org/index.php?topic=823.msg9557#msg9557), theymos. <del>Please release another release candidate when you have a moment if it is not included.</del><br /><br /><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9555#msg9555">Quote from: davidonpda on August 15, 2010, 10:02:05 PM</a></div><div class="quote">What about the transactions from 74000 to the invalid block. Are those all invalid now as well?<br /></div>Only the blocks including and after the invalid block are invalid. All previous blocks are valid.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>theymos</b> on <b>August 15, 2010, 10:06:02 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9555#msg9555">Quote from: davidonpda on August 15, 2010, 10:02:05 PM</a></div><div class="quote">What about the transactions from 74000 to the invalid block. Are those all invalid now as well?<br /></div><br />Only this aberrant transaction and coins generated after it in the block chain will be removed. All other transactions will continue to exist.<br /><br /><div class="quoteheader">Quote from: NewLibertyStandard</div><div class="quote">Will the bug fix include the 4-way SSE2 patch included in 0.3.9rc2?</div><br />It&#039;s included.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 10:13:43 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Oh, yeah, just noticed this topic. I can&#039;t remember when those block chains were snapshot, but I&#039;ll update it to be more descriptive (like block 64,000, etc.)<br /><br />Good thing I keep those around. &nbsp;;D<br /><br />My web server sits on a fiber, so it won&#039;t be a big deal everyone starts to download those files at once (at least for the more technical people).<br /><br />[edit] Shutting down all the remaining servers and super-nodes I left running. Hope that helps.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Insti</b> on <b>August 15, 2010, 10:17:25 PM</b>
					<hr />
					<div style="margin: 0 5ex;">knightmb, do you still have any of your monster network available to turn on to help build the new valid chain?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 10:18:17 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9560#msg9560">Quote from: Insti on August 15, 2010, 10:17:25 PM</a></div><div class="quote">knightmb, do you still have any of your monster network available to turn on to help build the new valid chain?<br /></div>Not anymore, was shutdown on the last day of the month for July, all I have left are about a 2 dozen servers, but near nothing of what I had before.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 10:27:26 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Here&#039;s something for your Signature if you&#039;re interested.<br /><br /><div class="codeheader">Code:</div><div class="code">[i][color=red][b]*** WARNING ***[/b][/color]&nbsp; DO NOT TRUST ANY TRANSACTIONS THAT HAPPENED AFTER 15.08.2010 17:05 UTC (block 74638). We are investigating a problem. ([url=http://bit.ly/afalQU]more[/url])[/i]</div><br />I shortened the URL since the signature can only contain 300 characters. Also, can we get some color on the news warning? It&#039;s not very noticeable.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 10:30:23 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I can build a block chain to the desired number using a combo of the old block chain and a client with the latest block chain (minus the bad stuff), what number should I shot for?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 10:31:07 PM</b>
					<hr />
					<div style="margin: 0 5ex;">74637 is the last good block</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 10:34:03 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9565#msg9565">Quote from: kencausey on August 15, 2010, 10:31:07 PM</a></div><div class="quote">74637 is the last good block<br /></div>Ok, good, I&#039;ve relabeled the old block chain on my site, I&#039;ll try to get as close to that number as I can. Basically, I&#039;m just loading up two clients, one with the old chain, another with the sorta bad chain at the end. I&#039;m going to let the first client get as close to the number as I can before stopping it. Then snapshot off that block chain. Since it does about 500 at a time, I&#039;ll probably be able to get it close to 74,501<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>BitLex</b> on <b>August 15, 2010, 10:35:48 PM</b>
					<hr />
					<div style="margin: 0 5ex;">i&#039;v got one of a w7-machine count 74602, if that helps.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 10:44:55 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9569#msg9569">Quote from: davidonpda on August 15, 2010, 10:41:29 PM</a></div><div class="quote">I already said that I have it right at 74637.<br /><br />Satoshi said it needs to be before 74,000<br /></div>So long as a the person who creates it has a patched client and downloads the whole chain, optimally from another computer on their local network, then it should stop at the right place automatically.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>BitLex</b> on <b>August 15, 2010, 10:52:47 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9569#msg9569">Quote from: davidonpda on August 15, 2010, 10:41:29 PM</a></div><div class="quote">Satoshi said it needs to be before 74,000<br /></div>He didn&#039;t, he said &quot;you&#039;ll want one&quot;, not that it <b>needs to be</b>, a little different.<br />and if &quot;..Only the blocks including and after the invalid block are invalid. All previous blocks are valid..&quot;, it doesn&#039;t need to be before 74000.<br /><br />just wanted to save knightmb some time, but yours is bigger than mine anyway.&nbsp; ;D</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 10:58:08 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Don&#039;t update the block chain download. &nbsp;When you take someone&#039;s block chain download, you don&#039;t want it right up to the end. &nbsp;A somewhat old one is better so it can download and verify the most recent blocks.<br /><br />tcatm&#039;s 4-way SSE2 SHA-256 is in the file sha256.cpp and already uploaded a few revs ago.<br /><br />I just now uploaded rev 134 which is the makefile.unix that enables building with it on Linux. &nbsp;If you build rev 134 on Linux now you&#039;ll get the -4way switch.<br /><br />If you have problems building because of it, then edit makefile.unix and:<br />- remove -DFOURWAYSSE2<br />- remove obj/sha256.o from the end of these lines:<br />bitcoin: $(OBJS) obj/ui.o obj/uibase.o obj/sha256.o<br />bitcoind: $(OBJS:obj/%=obj/nogui/%) obj/sha256.o<br /><br />The 0.3.10 linux build <i>will</i> have the -4way option when I build it.<br /><br />Here are the patch downloads for Windows:<br /><br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32-setup.exe<br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32.zip<br /><br />SHA1 16645ec5fcdb35bc54bc7195309a1a81105242bb bitcoin-0.3.10-win32-setup.exe<br />SHA1 4f35ad7711a38fe8c880c6c9beab430824c426d3 bitcoin-0.3.10-win32.zip<br /><br />Steps:<br />1) Shut down.<br />2) Download knightmb&#039;s blk files and replace your blk0001.dat and blkindex.dat files.<br />http://knightmb.dyndns.org/files/bitcoin/blocks/<br />http://rapidshare.com/files/413168038/BitcoinBlocks.torrent<br />3) Upgrade to 0.3.10.<br />4) It should start out with less than 74000 blocks and redownload the rest.<br /><br />Or if you don&#039;t want to mess with downloading blk files, you can just do this:<br /><br />1) Shut down.<br />2) Delete (or move) blk*.dat<br />3) Upgrade to 0.3.10.<br />4) It redownloads all blocks, probably take about an hour.<br /><br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 10:59:04 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Yeah, a little confusing &nbsp;???<br /><br />So I don&#039;t need to create one, or do I need to take what you guys already have and just throw it up on the FTP?<br /><br />Can you dump block data from a windows machine onto a Linux/Mac machine?<br /><br /><b>[edit]</b> Just saw your post, I&#039;ll build one to less than 74,000 then, should at least save you technical people a few minutes of downloading the new chain.&nbsp; ;)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Oh the Suspense!</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 15, 2010, 10:59:31 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><del>I can&#039;t stand the suspense! Do any Jr. Members or higher happen to have an unofficial SVN rev 134 Linux 64-bit build compiled that they&#039;d be willing to share? Yeah, I know the official build is about to be released in a few minutes. It&#039;s not terribly important.<br /><br />Edit: Updated the SVN version number as per satoshi&#039;s comment a moment ago.</del><br /><br />Ah, never mind. Since the SVN version was just updated and the Windows builds were just released, I&#039;ll wait. :-[</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 11:17:24 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9574#msg9574">Quote from: knightmb on August 15, 2010, 10:59:04 PM</a></div><div class="quote"><b>[edit]</b> Just saw your post, I&#039;ll build one to less than 74,000 then, should at least save you technical people a few minutes of downloading the new chain. &nbsp;;)<br /></div>Just leave the old one alone! &nbsp;Older is better. &nbsp;What block number is it? &nbsp;Anywhere from 60000-74000 is good.&nbsp; The one that you&#039;ve had available for a while has been vetted and is the best choice.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 11:18:34 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I just used your old file knightmb and on a rather old system it didn&#039;t take me very long to catch up, so I&#039;m inclined to say &quot;don&#039;t bother&quot;.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>theymos</b> on <b>August 15, 2010, 11:21:06 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9576#msg9576">Quote from: satoshi on August 15, 2010, 11:17:24 PM</a></div><div class="quote">What block number is it?<br /></div><br />It&#039;s around 67k. It only took me about 3 minutes to get to the current block.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>HostFat</b> on <b>August 15, 2010, 11:32:43 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I think that you should add something about this: http://bitcointalk.org/index.php?topic=259.0<br />There must be a label on the client that show a warning message if needed :)<br />Now everyone have always to check the website, and I think that this is bad.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 11:35:39 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Cool, works for me!&nbsp; ;D</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 11:36:10 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Starting at 67000 is <i>perfect</i>. &nbsp;<br /><br />Yeah, at the moment you&#039;ll stop at 74638. &nbsp;It should start slowly creeping up as more nodes upgrade and generate.<br /><br />Linux build links below.<br /><br />The Linux version includes tcatm&#039;s 4-way SSE2 SHA-256 that makes generating faster on i5 and AMD CPU&#039;s. &nbsp;Use the &quot;-4way&quot; switch to enable it and check if it&#039;s faster for you.<br /><br />Download links:<br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32-setup.exe<br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32.zip<br />http://www.bitcoin.org/download/bitcoin-0.3.10-linux.tar.gz<br /><br />SHA1 16645ec5fcdb35bc54bc7195309a1a81105242bb bitcoin-0.3.10-win32-setup.exe<br />SHA1 4f35ad7711a38fe8c880c6c9beab430824c426d3 bitcoin-0.3.10-win32.zip<br />SHA1 e3fda1ddb31b0d5c35156cacd80dee6ea6ae6423 bitcoin-0.3.10-linux.tar.gz</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 15, 2010, 11:37:07 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9582#msg9582">Quote from: Joozero on August 15, 2010, 11:32:43 PM</a></div><div class="quote">I think that you should add something about this: http://bitcointalk.org/index.php?topic=259.0<br />There must be a label on the client that show a warning message if needed :)<br />Now everyone have always to check the website, and I think that this is bad.<br /></div>Agree, wanted to do that for a long time, haven&#039;t had time to do it.<br /><br />For now, you could also subscribe to the bitcoin-list mailing list.&nbsp; It rarely gets used except for announcements like this and major new versions.<br /><br />Subscribe/unsubscribe page:<br />http://lists.sourceforge.net/mailman/listinfo/bitcoin-list<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 15, 2010, 11:37:40 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9576#msg9576">Quote from: satoshi on August 15, 2010, 11:17:24 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9574#msg9574">Quote from: knightmb on August 15, 2010, 10:59:04 PM</a></div><div class="quote"><b>[edit]</b> Just saw your post, I&#039;ll build one to less than 74,000 then, should at least save you technical people a few minutes of downloading the new chain. &nbsp;;)<br /></div>Just leave the old one alone! &nbsp;Older is better. &nbsp;What block number is it? &nbsp;Anywhere from 60000-74000 is good.&nbsp; The one that you&#039;ve had available for a while has been vetted and is the best choice.<br /></div>I&#039;ve put the block number with the file, so you&#039;ll know exactly where each stops at.&nbsp; <br /><br />BitCoinBlocks_Linux_67309.zip<br />BitCoinBlocks_Windows_67300.zip<br /><br />I&#039;ve leave them be. Glad to know I could help&nbsp; :)<br /><br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 11:45:26 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9580#msg9580">Quote from: davidonpda on August 15, 2010, 11:31:37 PM</a></div><div class="quote">... It already is on block 74638. I assume that means that block is now a good one?<br /></div><br />I had some confusion on this myself and got clarification in #bitcoin-dev:<br /><br />The bad block was number 74638, the last good one was 74637.&nbsp; The numbers start at 0, so when your client shows there are 74638 blocks then that means you have up to block number 74637, the last good one.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>HostFat</b> on <b>August 15, 2010, 11:47:58 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader">Quote</div><div class="quote">Agree, wanted to do that for a long time, haven&#039;t had time to do it.<br /><br />For now, you could also subscribe to the bitcoin-list mailing list. &nbsp;It rarely gets used except for announcements like this and major new versions.<br /><br />Subscribe/unsubscribe page:<br />http://lists.sourceforge.net/mailman/listinfo/bitcoin-list<br /></div><br />Good :D<br /><br />Anyway <b>I usually</b> check the website, I was thinking to a solution for newbie-users ( that they are more to come on future )<br />A small bug can be a big problem with a network with a lot of newbie and/or not-informed users. ( and none of them will ever give a look to a source like this: http://lists.sourceforge.net/mailman/listinfo/bitcoin-list :P )<br /><br />( sorry for my english, I hope you are still understanding me ;D )</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 15, 2010, 11:59:36 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Updated and combined instructions:<br /><br />1. &nbsp;Stop generating immediately, close your current client if you have not updated to 0.3.10.<br /><br />2. &nbsp;Download 0.3.10:<br /><br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32-setup.exe<br />http://www.bitcoin.org/download/bitcoin-0.3.10-win32.zip<br />http://www.bitcoin.org/download/bitcoin-0.3.10-linux.tar.gz<br /><br />SHA1 16645ec5fcdb35bc54bc7195309a1a81105242bb bitcoin-0.3.10-win32-setup.exe<br />SHA1 4f35ad7711a38fe8c880c6c9beab430824c426d3 bitcoin-0.3.10-win32.zip<br />SHA1 e3fda1ddb31b0d5c35156cacd80dee6ea6ae6423 bitcoin-0.3.10-linux.tar.gz<br /><br />3. (optional) &nbsp;Download a previously known good blockchain:<br /><br />http://knightmb.dyndns.org/files/bitcoin/blocks/<br />http://rapidshare.com/files/413168038/BitcoinBlocks.torrent<br /><br />and replace your blk0001.dat and blkindex.dat files with those from the relevant download for your platform.<br /><br />3b. &nbsp;If you don&#039;t download, delete or move the blk0001.dat and blkindex.dat files.<br /><br />4. &nbsp;Start 0.3.10 and watch it catch up to block 74637 and beyond and help restart things.<br /><br /><b>Edit:</b><br /><b>Edit 2: Add more explanation</b><br /><br />4b. &nbsp;Currently the network has a combination of good and bad nodes (those running versions older than 0.3.10). &nbsp;If you only connect to nodes running old versions, you will be stuck at 74638 blocks. &nbsp;You can fix this by running the client with the options &quot;-addnode=75.158.131.108 -addnode=99.27.237.13 -addnode=76.235.234.64 -addnode=74.137.15.169 -addnode=68.68.99.14&quot;.&nbsp; This specifically connects you to a number of &#039;known good&#039; nodes and ensures that you receive transactions generated within the network of updated clients.&nbsp; As the number of out of date clients in the network decreases, this will become unnecessary.&nbsp; If you want more nodes or just different ones, you can find a larger list at http://www.bitcoin.org/wiki/doku.php?do=show&amp;id=74638_nodes .</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>BitLex</b> on <b>August 16, 2010, 12:12:36 AM</b>
					<hr />
					<div style="margin: 0 5ex;">my forwarded node counts 74642 as i type (36conn.),<br />3 other nodes are still at 74638 (8conn. each)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 16, 2010, 12:20:59 AM</b>
					<hr />
					<div style="margin: 0 5ex;">Ya know, in a way, this actually temporarily decreases the difficulty to generate blocks until everyone upgrades. Yeah, it&#039;ll be slower, but that just gives each client more time to try to generate the difficult hash.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Ground Loop</b> on <b>August 16, 2010, 12:29:55 AM</b>
					<hr />
					<div style="margin: 0 5ex;">Question about fallout:&nbsp; I had a transaction that I submitted after the bad block, using the bad block chain.<br /><br />What is the status of that transaction?<br />From what I can tell, my (updated) sending client wallet shows the deducted amount.<br /><br />Will it get reincorporated into the fixed chain, and will the recipient be able to spend it?<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kosovito</b> on <b>August 16, 2010, 12:39:17 AM</b>
					<hr />
					<div style="margin: 0 5ex;">I did all steps, now my client is 0.3.10 and it stopped at block 74638. Is all fine?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 01:00:45 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9609#msg9609">Quote from: Ground Loop on August 16, 2010, 12:29:55 AM</a></div><div class="quote">Question about fallout: &nbsp;I had a <b>transaction</b> that I submitted after the bad block, using the bad block chain.<br /><br />What is the status of that transaction?<br />From what I can tell, my (updated) sending client wallet shows the deducted amount.<br /><br />Will it get reincorporated into the fixed chain, and will the recipient be able to spend it?<br /></div>Right, it will get reincorporated into the fixed chain. &nbsp;The transaction won&#039;t disappear, it&#039;ll still be visible on both sides, but the confirmation count will jump back to 0 and start counting up again.<br /><br />It&#039;s only if you generated a block in the bad chain after block 74638 that the 50 BTC from that will disappear. &nbsp;Any blocks in the bad chain wouldn&#039;t have matured yet. </div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 01:02:24 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9615#msg9615">Quote from: kosovito on August 16, 2010, 12:39:17 AM</a></div><div class="quote">I did all steps, now my client is 0.3.10 and it stopped at block 74638. Is all fine?<br /></div>If you still show 74638 blocks then you aren&#039;t connected to any 0.3.10 nodes. &nbsp;<br /><br />For today, try adding these parameters:&nbsp; <br />-addnode=75.158.131.108 -addnode=99.27.237.13 -addnode=68.68.99.14<br /><br />See<br />http://bitcointalk.org/index.php?topic=828</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>GoldRush</b> on <b>August 16, 2010, 01:02:35 AM</b>
					<hr />
					<div style="margin: 0 5ex;">Most people running clients are not reading this message thread. &nbsp;So... &nbsp;Silly questions:<br /><br />1) How will this continue to affect version 3.8.1 (pre-catastrophe) clients with bad block chain?<br />2) How will this affect clients that upgrade to 3.8.10 but don&#039;t remove their block chain files?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>kencausey</b> on <b>August 16, 2010, 01:06:13 AM</b>
					<hr />
					<div style="margin: 0 5ex;">I added the addnode options and info about the &#039;stuck at 74638 blocks&#039; issue at http://bitcointalk.org/index.php?topic=823.msg9595#msg9595</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 01:12:05 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9625#msg9625">Quote from: trebronics on August 16, 2010, 01:02:35 AM</a></div><div class="quote">Most people running clients are not reading this message thread. &nbsp;So... &nbsp;Silly questions:<br /><br />1) How will this continue to affect version 3.8.1 (pre-catastrophe) clients with bad block chain?<br />2) How will this affect clients that upgrade to 3.8.10 but don&#039;t remove their block chain files?<br /></div>1) Once more than 50% of the node power is upgraded and the good chain overtakes the bad, the 0.3.10 nodes will make it hard for any bad transactions to get any confirmations. <br />2) If you didn&#039;t remove your blk*.dat files, you&#039;re not helping to contribute to that 50%, and you&#039;ll still show bad transactions until the good chain overtakes the bad chain.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Ground Loop</b> on <b>August 16, 2010, 02:02:07 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9606#msg9606">Quote from: NewLibertyStandard on August 16, 2010, 12:20:59 AM</a></div><div class="quote">Ya know, in a way, this actually temporarily decreases the difficulty to generate blocks until everyone upgrades. Yeah, it&#039;ll be slower, but that just gives each client more time to try to generate the difficult hash.<br /></div><br />Of course, this happened right after the difficulty kicked up to 511.7, so all these new &quot;good&quot; blocks will have to contend with that.&nbsp; And a good chunk of the network grind power is off on the wrong chain, so new blocks may take a lot longer than 10min to find.&nbsp; At what point will the balancing figure this out and possibly kick the difficulty back down again?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 02:16:10 AM</b>
					<hr />
					<div style="margin: 0 5ex;">The bad chain is also slowed down as more nodes upgrade.<br /><br />We&#039;ve already generated 14 blocks since 74638. &nbsp;The builds of 0.3.10 were uploaded about 2 and 3 hours ago. &nbsp;Of the nodes I&#039;m connected to, more than half are already 0.3.10. &nbsp;I would say we probably already have more power than the bad chain.<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 16, 2010, 02:22:05 AM</b>
					<hr />
					<div style="margin: 0 5ex;">I&#039;m chucking as much CPU at this as I can. &nbsp;Yeah, bit of an unfair advantage I guess until everyone upgrades. &nbsp;:-X<br />My wife&#039;s PC already generated 2 of the new blocks (LOL), luck is on her side I guess.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>lachesis</b> on <b>August 16, 2010, 02:28:57 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9642#msg9642">Quote from: satoshi on August 16, 2010, 02:16:10 AM</a></div><div class="quote">... Of the nodes I&#039;m connected to, more than half are already 0.3.10. ...<br /></div>That&#039;s great news! How did you figure that out, though? I was considering writing a client specially tailored to put itself out there and try to get as many people to connect as possible, then survey their versions and write out a log (in addition to all the normal bitcoin stuff).</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 02:38:21 AM</b>
					<hr />
					<div style="margin: 0 5ex;">On Windows, findstr /c:&quot;version message&quot; debug.log<br /><br />It looks like the bad chain was on block 74678 recently. &nbsp;Can&#039;t wait to overtake it.<br /><br />On the stats at http://nullvoid.org/bitcoin/statistix.php&nbsp; there&#039;s been 5 blocks per hour in the last 3 hours. &nbsp;We had a difficulty adjustment about a day ago that should have put it back to 6 blocks per hour.<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>bdonlan</b> on <b>August 16, 2010, 02:39:55 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9642#msg9642">Quote from: satoshi on August 16, 2010, 02:16:10 AM</a></div><div class="quote">The bad chain is also slowed down as more nodes upgrade.<br /><br />We&#039;ve already generated 14 blocks since 74638. &nbsp;The builds of 0.3.10 were uploaded about 2 and 3 hours ago. &nbsp;Of the nodes I&#039;m connected to, more than half are already 0.3.10. &nbsp;I would say we probably already have more power than the bad chain.<br /><br /></div>I think it&#039;d probably be a good idea still to come out with another version that rejects connections from older versions - otherwise the network might remain rather fragmented for a while. :/</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>mizerydearia</b> on <b>August 16, 2010, 02:50:00 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9595#msg9595">Quote from: kencausey on August 15, 2010, 11:59:36 PM</a></div><div class="quote">4b. &nbsp;Currently the network has a combination of good and bad nodes (those running versions older than 0.3.10). &nbsp;If you only connect to nodes running old versions, you will be stuck at 74638 blocks. &nbsp;You can fix this by running the client with the options &quot;-addnode=75.158.131.108 -addnode=99.27.237.13 -addnode=76.235.234.64 -addnode=74.137.15.169 -addnode=68.68.99.14&quot;<br /></div><br />http://www.bitcoin.org/wiki/doku.php?do=show&amp;id=74638_nodes</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 16, 2010, 03:09:52 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9649#msg9649">Quote from: bdonlan on August 16, 2010, 02:39:55 AM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9642#msg9642">Quote from: satoshi on August 16, 2010, 02:16:10 AM</a></div><div class="quote">The bad chain is also slowed down as more nodes upgrade.<br /><br />We&#039;ve already generated 14 blocks since 74638. &nbsp;The builds of 0.3.10 were uploaded about 2 and 3 hours ago. &nbsp;Of the nodes I&#039;m connected to, more than half are already 0.3.10. &nbsp;I would say we probably already have more power than the bad chain.<br /><br /></div>I think it&#039;d probably be a good idea still to come out with another version that rejects connections from older versions - otherwise the network might remain rather fragmented for a while. :/<br /></div>We want to keep the older clients connected so that when the correct chain overtakes the incorrect chain, they will switch back to the correct chain. Although I don&#039;t know the specifics of how far back in the chain the old chain will accept a branched chain.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>knightmb</b> on <b>August 16, 2010, 03:57:39 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9657#msg9657">Quote from: NewLibertyStandard on August 16, 2010, 03:09:52 AM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9649#msg9649">Quote from: bdonlan on August 16, 2010, 02:39:55 AM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9642#msg9642">Quote from: satoshi on August 16, 2010, 02:16:10 AM</a></div><div class="quote">The bad chain is also slowed down as more nodes upgrade.<br /><br />We&#039;ve already generated 14 blocks since 74638. &nbsp;The builds of 0.3.10 were uploaded about 2 and 3 hours ago. &nbsp;Of the nodes I&#039;m connected to, more than half are already 0.3.10. &nbsp;I would say we probably already have more power than the bad chain.<br /><br /></div>I think it&#039;d probably be a good idea still to come out with another version that rejects connections from older versions - otherwise the network might remain rather fragmented for a while. :/<br /></div>We want to keep the older clients connected so that when the correct chain overtakes the incorrect chain, they will switch back to the correct chain. Although I don&#039;t know the specifics of how far back in the chain the old chain will accept a branched chain.<br /></div>The old clients should accept it all the way back to the last snapshot of release, so this being found so quickly and so long after the last release, it should work in theory. Here&#039;s a good test of the theory&nbsp; ;D</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>Ground Loop</b> on <b>August 16, 2010, 05:07:50 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9623#msg9623">Quote from: satoshi on August 16, 2010, 01:00:45 AM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9609#msg9609">Quote from: Ground Loop on August 16, 2010, 12:29:55 AM</a></div><div class="quote">Question about fallout: &nbsp;I had a <b>transaction</b> that I submitted after the bad block, using the bad block chain.<br /><br />What is the status of that transaction?<br />From what I can tell, my (updated) sending client wallet shows the deducted amount.<br /><br />Will it get reincorporated into the fixed chain, and will the recipient be able to spend it?<br /></div>Right, it will get reincorporated into the fixed chain. &nbsp;The transaction won&#039;t disappear, it&#039;ll still be visible on both sides, but the confirmation count will jump back to 0 and start counting up again.<br /><br />It&#039;s only if you generated a block in the bad chain after block 74638 that the 50 BTC from that will disappear. &nbsp;Any blocks in the bad chain wouldn&#039;t have matured yet. <br /></div><br />Interesting.. fascinating to watch this work its way through the bowels of the system.<br />It was block 73746 that I generated.<br />&nbsp; &nbsp; CTxOut(nValue=50.00000000, scriptPubKey=0x8DDD5C7DADB2D43AC5F186)<br />08/12/10 02:35 generated 50.00<br /><br />And I sent 49.00 of it to 19Nzg21hQQDAY5GTdTTuUVPA4MaE7AusXz (using the broken chain)<br /><br />Now I&#039;m waiting for that node to figure out it was received, and it&#039;s using the new chain.<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 12:59:38 PM</b>
					<hr />
					<div style="margin: 0 5ex;">It looks like we overtook the bad chain somewhere around 74689.&nbsp; 0.3.9 and lower nodes have been responding with the current block number for some hours now.<br /><br />That means it&#039;s no longer necessary to delete blk*.dat before upgrading.&nbsp; You can just upgrade and it&#039;ll reorg away the bad block chain.<br /><br />Thanks to everyone for the quick response!</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>throughput</b> on <b>August 16, 2010, 02:35:10 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Would it be useful to have RPC command to chop off the tail of the chain manually,<br />instead of removind and redownloading the whole chain?<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>laszlo</b> on <b>August 16, 2010, 10:13:00 PM</b>
					<hr />
					<div style="margin: 0 5ex;">So at this point, would a client that has not upgraded also have the correct chain?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>NewLibertyStandard</b> on <b>August 16, 2010, 10:15:32 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=823.msg9833#msg9833">Quote from: laszlo on August 16, 2010, 10:13:00 PM</a></div><div class="quote">So at this point, would a client that has not upgraded also have the correct chain?<br /></div>Yes. The only exception would be if an unpatched client made another fake transaction and managed to verify it. They would be able to spread that fake block to a few other nodes that haven&#039;t upgraded, but the upgraded clients seem to have more power than the unpatched clients, so the bad link would not last long and would not be spread by upgraded clients.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: overflow bug SERIOUS</b><br />
					Post by: <b>satoshi</b> on <b>August 16, 2010, 10:54:55 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Un-upgraded nodes have the correct chain most of the time, but they are still trying to include the overflow transaction in every block, so they&#039;re continually trying to fork and generate invalid blocks.&nbsp; If an old version node is restarted, its transaction pool is emptied, so it may generate valid blocks for a while until the transaction gets broadcast again.&nbsp; 0.3.9 and lower nodes still must upgrade.<br /><br />The SVN now has the code we needed to automatically reorg the block chain without having to delete the blk*.dat files manually.&nbsp; I knew I couldn&#039;t write that code fast and carefully enough yesterday, so I went with the quick manual option.</div>
					<br /><br />
					<div align="center" class="smalltext">
		<span class="smalltext" style="display: inline; visibility: visible; font-family: Verdana, Arial, sans-serif;"><a href="http://www.simplemachines.org/" title="Simple Machines Forum" target="_blank">Powered by SMF 1.1.19</a> | 
<a href="http://www.simplemachines.org/about/copyright.php" title="Free Forum Software" target="_blank">SMF &copy; 2006-2009, Simple Machines</a>
		</span></div>
				</td>
			</tr>
		</table>
++++
