=== Gregory Maxwell - A trip to the moon requires a rocket with multiple stages ...

****
* Source: https://www.reddit.com/r/Bitcoin/comments/438hx0/a_trip_to_the_moon_requires_a_rocket_with/
* Author: Gregory Maxwell (nullc)
* Date copied: 2022-05-26
****

==== A trip to the moon requires a rocket with multiple stages or otherwise the rocket equation will eat your lunch... packing everyone in clown-car style into a trebuchet and hoping for success is right out.

A lot of people on Reddit think of Bitcoin primarily as a competitor to
card payment networks. I think this is more than a little odd-- Bitcoin
is a digital _currency_. Visa and the US dollar are not usually
considered competitors, Mastercard and gold coins are not usually
considered competitors. Bitcoin isn't a front end for something that
provides credit, etc.

Never the less, some are mostly interested in Bitcoin for payments
(https://bitcointalk.org/index.php?topic=204.msg1714#msg1714[not a new
phenomenon])-- and are not so concerned about what are, in my view,
Bitcoin's primary distinguishing values-- monetary sovereignty,
censorship resistance, trust cost minimization, international
accessibility/borderless operation, etc. (Or other areas we need to
improve, like personal and commercial privacy) Instead some are very
concerned about Bitcoin's competitive properties compared to legacy
payment networks. ... And although consumer payments are only one small
part of whole global space of money, ... money gains value from network
effects, and so I would want all the "payments only" fans to love
Bitcoin too, even if I didn't care about payments.

But what does it mean to be seriously competitive in that space? The
existing payments solutions have huge deployed infrastructure and
merchant adoption-- lets ignore that. What about capacity? Combined the
major card networks are now doing something on the other of 5000
transactions per second on a year round average; and likely something on
the order of 120,000 transactions per second on peak days.

The decentralized Bitcoin blockchain is globally shared broadcast
medium-- probably the most insanely inefficient mode of communication
ever devised by man. Yet, considering that, it has some impressive
capacity. But relative to highly efficient non-decentralized networks,
not so much. The issue is that in the basic Bitcoin system every node
takes on the whole load of the system, that is how it achieves its
monetary sovereignty, censorship resistance, trust cost minimization,
etc. Adding nodes increases costs, but not capacity. Even the most
[line-through]*reckless* hopeful blocksize growth numbers don't come
anywhere close to matching those TPS figures. And even if they did, card
processing rates are rapidly increasing, especially as the developing
world is brought into them-- a few more years of growth would have their
traffic levels vastly beyond the Bitcoin figures again.

No amount of spin, inaccurately comparing a global broadcast consensus
system to loading a webpage changes any of this.

So-- Does that mean that Bitcoin can't be a big winner as a payments
technology? No. But to reach the kind of capacity required to serve the
payments needs of the world we must work more intelligently.

From its very beginning Bitcoin was design to incorporate layers in
secure ways through its smart contracting capability (What, do you think
that was just put there so people could wax-philosophic about
meaningless "DAOs"?). In effect we will use the Bitcoin system as a
highly accessible and perfectly trustworthy robotic judge and conduct
most of our business outside of the court room-- but transact in such a
way that if something goes wrong we have all the evidence and
established agreements so we can be confident that the robotic court
will make it right. (Geek sidebar: If this seems impossible, go read
this old post on
https://bitcointalk.org/index.php?topic=281848.0[transaction
cut-through])

This is possible precisely because of the core properties of Bitcoin. A
censorable or reversible base system is not very suitable to build
powerful upper layer transaction processing on top of... and if the
underlying asset isn't sound, there is little point in transacting with
it at all.

The science around Bitcoin is new and we don't know exactly where the
breaking points are-- I hope we never discover them for sure-- we do
know that at the current load levels the decentralization of the system
has not improved as the users base has grown (and appear to have reduced
substantially: even businesses are largely relying on third party
processing for all their transactions; something we didn't expect early
on).

There are many ways of layering Bitcoin, with varying levels of
security, ease of implementation, capacity, etc. Ranging from the
strongest-- bidirectional payment channels (often discussed as the
'lightning' system), which provide nearly equal security and
anti-censorship while also adding instantaneous payments and improved
privacy-- to the simplest, using centralized payment processors, which I
believe are (in spite of my reflexive distaste for all things
centralized) a perfectly reasonable thing to do for low value
transactions, and can be highly cost efficient. Many of these approaches
are competing with each other, and from that we gain a vibrant ecosystem
with the strongest features.

Growing by layers is the gold standard for technological innovation.
It's how we build our understanding of mathematics and the physical
sciences, it's how we build our communications protocols and networks...
Not to mention payment networks. Thus far a
https://en.wikipedia.org/wiki/Multistage_rocket[multi-staged] approach
has been an integral part of the
https://en.wikipedia.org/wiki/Tsiolkovsky_rocket_equation[design of
rockets] which have, http://xkcd.com/893/[from time to time], brought
mankind to the moon.

Bitcoin does many unprecedented things, but this doesn't release it from
physical reality or from the existence of engineering trade-offs. It is
not acceptable, in the mad dash to fulfill a particular application set,
to turn our backs on the fundamentals that make the Bitcoin currency
valuable to begin with-- especially not when established forms in
engineering already tell us the path to have our cake and eat it too--
harmoniously satisfying all the demands.

Before and beyond the layers, there are other things being done to
improve capacity-- e.g. Bitcoin Core's
https://bitcoincore.org/en/2015/12/21/capacity-increase/[capacity plan]
from December (see also: the
https://bitcoincore.org/en/2015/12/23/capacity-increases-faq/[FAQ])
proposes some new improvements and inventions to nearly double the
system's capacity while offsetting many of the costs and risks, in a
fully backwards compatible way. ... but, at least for those who are
focused on payments, no amount of simple changes really makes a
difference; not in the way layered engineering does.
