=== ZmnSCPxj - Who Am I?

****
* Source: https://zmnscpxj.github.io/about.html
* Author: ZmnSCPxj
* Date copied: 2022-06-08
****

I am ZmnSCPxj, a randomly-generated Internet person. My pronouns are
he/him/his.

I understand that humans instinctively desire to know my identity.
However, I think my identity is largely immaterial, and prefer to be
judged by my work.

If you are wondering whether to donate or not, and wondering what my
cost of living or my income is, please understand that properly
speaking, you should donate to me based on the utility you find my
articles and my work on Bitcoin and the Lightning Network.

==== A Short Rant on Cost-of-Living

The actual cost-of-living for all human beings is constant regardless of
location.

Places where it is pleasant to live due to weather, local governance,
availability of civilization, political stability, and so on, have
higher cost-of-living than places without such amenities. It then
follows that humans with low cost-of-living are still paying as if they
are in the place with maximum cost-of-living; they are simply paying by
suffering from a lack of such pleasantness in their lives.

Thus, if you are ever in a position to provide economic sustenance to
some human in compensation for the work they do, I implore you to
specifically ignore the cost-of-living of that human.

It is therefore quite appropriate that I should not have to reveal such
details in order to encourage or discourage you from donating or
otherwise supporting me.

==== Who Am I Not?

I am _not_ any of the following people:

* Tom Elvis Jedusor
* Craig S. Wright
* Luke Dash, Jr.
* DJ Ertegun

Of note, is that there is no way to prove non-identity, only to prove
identity. Thus, you cannot verify that I am not any of the above.

==== Accounts

Below are various accounts I control:

* Protonmail mailto:ZmnSCPxj%20atsign%20proton%20mail%20dotcom[ZmnSCPxj
atsign proton mail dotcom]
* Github https://github.com/ZmnSCPxj[ZmnSCPxj]
* Reddit https://reddit.com/u/ZmnSCPxj[/u/ZmnSCPxj]
* Bitcointalk
https://bitcointalk.org/index.php?action=profile;u=1815920[ZmnSCPxj]
* LightningWiki.net
https://lightningwiki.net/index.php/User:ZmnSCPxj[User:ZmnSCPxj]
* BitcoinHackers.org Mastodon
https://bitcoinhackers.org/@ZmnSCPxj[@ZmnSCPxj]

Of note, is that a Twitter https://twitter.com/zmnscpxj[@ZmnSCPxj]
exists, but I do not control this account. So far (2019-04-03), as far
as I know, its controller has done nothing I would find objectionable,
so I presume it is a fan who simply protected this account on my behalf.
