=== Peter Todd - The Essence of Bitcoin

****
* Source: https://www.whatbitcoindid.com/podcast/peter-todd-on-the-essence-of-bitcoin
* Author: Peter Todd, interviewed by Peter McCormack
* Date copied: 2022-05-25
****

*Peter McCormack:* Hi there,
Peter. How are you?

*Peter Todd:* I’m great, thanks.

*Peter McCormack:* Thank you for
coming on the podcast. I’ve wanted to talk to you for quite a long time.
I followed a lot of your work. And, one of the things that really stood
out for me is when I went on your blog, and not only did I not
understand the content of your articles, I didn’t even understand what
they were about.

Like there’s a certain level of technical competence that I think you
have to have to kind of understand this work. And, I then read about a
story that you were emailing Hal Finney and Adam Back when you were at
like 15?

*Peter Todd:* Yep.

*Peter McCormack:* I’ve got to
ask about this. What’s the background? How does a 15-year-old start
talking to Hal Finney and Adam Berk about Hashcash? What’s the journey
to that?

*Peter Todd:* Well, the great thing
with the Internet is, no one knows that you’re dark, and even when they
do, they don’t care. And I mean, if you go back far enough, as a young
kid, I watched a lot of Star Trek and thought the ideals of democracy
and freedom of speech, they’re all said and well and good.

And, my dad’s an economist by training. So initially, really early on, I
got interested in the freedom project, which is a decentralised
censorship resistant publication network. Long story short is, it lets
you make a website that no one can take down, lets you publish.

And I thought, “Oh! That’s really cool.” And, got interested in it, did
a little bit of work on it. So actually, first time I kind of worked on
creating an exploit, was actually against Freenet. The work I created a
tool to go and map out the interconnections of different nodes, so those
are all well and interesting.

But, I think the big issue with Freenet network, was, as I was thinking
to myself, “Well, obviously the next step is you need decentralised
money. Just being able to publish your thoughts isn’t enough. Political
movements need money. Take a look, political movements for the
marginalised, the poor.

If you’re a rich person, you have the way of funding the things you need
to fund to make your political movement happen, whereas the poor don’t
have that. We are often kind of talking about it in reverse, the rich
will gain politics, and so on. And, reality, I mean you can’t kind of
stop that. But, for the disadvantage, you definitely need that option to
be able to move money around. You need to be able to without
surveillance.

So, I think long story short is, somehow or another, I wanted upon a
mailing list, the Blue Sky mailing list, which if I remember correctly,
it was advertised on the Freenet mailing lists. So, I signed up, we
started talking about stuff, and I spent a lot of time trying to invent
Bitcoin, and like many people completely failed at it.

And, it’s really interesting looking back and seeing just how wrong I
was, in almost 180 degrees offset what was the right answer. And, a lot
of people, I think, had that experience.

*Peter McCormack:* So you tried
to invent a Bitcoin?

*Peter Todd:* Yeah. I was one of
many, many people trying to create decentralised currency. And, really
failed at us.

*Peter McCormack:* What was
version?

*Peter Todd:* Well, I think … I
mean, I didn’t have a proposal, ’cause I realised all my thoughts on it
weren’t going to work. But, I think what I caught so wrong was I had
thought about Hashcash in terms of the thing that controls the creation
of money. And, that’s not actually an important thing. The creation of
money is not the important thing. It’s preventing double-spending that
is.

The creation is just a onetime event. Allowing money to be moved
consistently, and accurately without double spend, is actually the
critical thing. And, unfortunately, because I tied proof of works to the
creation so tightly, I never really came up with the concept of, “Well
hang on.” No, no. We tied proof of work to the changes in the ledger, to
make sure it’s difficult three or at the changes.

*Peter McCormack:* Right.

*Peter Todd:* And, my thinking on my
kind of solution where we have some kind of decentralised database, how
do you do that? I don’t know. It can be attacked, it can be civil
attacked. And, I just constantly shot down ideas, and could never figure
out, how do you make this work, when the answer was juts so simple. But,
it was 180 degrees opposite what I was working on.

*Peter McCormack:* But, I’m
guessing you’re saying it’s simple ’cause the answer was Bitcoin, right?

*Peter Todd:* I mean, literally
someone could have sat down … Like honestly, it’s to the point where one
tweet from the future, saying how Bitcoin works, would probably have
been enough info for me to have created Bitcoin.

*Peter McCormack:* But, what is
the key, the one key element then?

*Peter Todd:* Using proof of work to
make changes to the ledger difficult. That one sentence, I think,
encapsulates the key part of Bitcoin that we were missing back then.

*Peter McCormack:* So, it’s more
the game theory than the code?

*Peter Todd:* I don’t even … The
point is, I don’t even think the game theory part is a really critical
thing. Like, absolute core of it that you must have is tying proof work
to changes to the ledger, to make it expensive to change. You could
probably have Bitcoin without even a financial reward. It would still
work far better than any of the crazy ideas people had come up back
then.

*Peter McCormack:* So, the
Bitcoin white paper comes out, you’re obviously are aware of it, you
read it. Is it obvious at the time or?

*Peter Todd:* Absolutely.

*Peter McCormack:* Oh,
immediately you could?

*Peter Todd:* Yeah. For me, I
believe I read the Bitcoin white paper for the first time, like late
2009. And, I remember, you know when I read it, I was like, “Oh, shit! I
should’ve thought of that.” It was actually, for me, it was opposite
many people.

For me, I read it, and this is obviously gonna work. And, only later did
I come up with reasons why it wouldn’t.

*Peter McCormack:* Right.

*Peter Todd:* Whereas, for many
people, they read and think, “How would this ever work?” And then, later
they’re convinced it does. But, I’d been primed, ’cause I’d already
worked on this and tried very hard. So, when I saw it that’s … It just
was so obvious to me. “Oh, I was wrong. This was the missing piece”

*Peter McCormack:* How, as a
15-year-old, do you make the leap from realising that there is a need
for money to finance certain projects and things, to it must be having
to be a decentralised type of money that doesn’t already exist? How do
you make that leap?

*Peter Todd:* I mean, the idea of
e-money and cypherpunk stuff around that was not exactly like an unknown
concept. I partly even read Sci Fi stories at the time talking about
that. The notion of credits is really sort of a common term in Sci Fi
stories. I mean. it’s just …

And also, money itself has a property. I mean, sure, it’s issued by the
government, but paper money I can give to you, and no one can stop me.
The idea that money would have to be controlled on transaction basis is
this very new thing, pushed by big companies who want to go make money
off this, and Law enforcement who would like to surveil everyone. This
is the opposite of how money should work. This is not the status quo.

*Peter McCormack:* So, this
Bitcoin worked then, or is it working?

*Peter Todd:* I mean, in terms of
doing what money should do, it’s a hell of a lot closer than say PayPal.
It’s a lot closer to what PayPal was meant to be. I mean, people who
started PayPal wanted to create censorship resistant e-currencies. They
didn’t have the tech to do it, and they didn’t have the legal frameworks
to get away with it.

So, they didn’t. But, that was the initial concept with PayPal. So,
Bitcoin’s a lot close to that. I mean, Bitcoin has scaled boldy
problems. But, the core thing of what Bitcoin does is much closer to
that than alternatives, certainly closer to things like Liberty Reserve,
which of course got shut down.

*Peter McCormack:* Yeah, I guess
there’s always been the centralised problem, right?

*Peter Todd:* Yeah. Centralisation
kills things if they have adversaries. Often centralisation’s way to go.
I mean, I have approached it myself, called Open TimeStamps, which is
absolutely centralised. There are four calendars of the Open timeStamps
system. I run two of them, two other people run another two.

It’s a centralised system. But, Open TimeStamps doesn’t really have
adversaries in this way that Bitcoin does. And, no one’s going to profit
by shutting down Open TimeStamps in the way you would with Bitcoin.

And also, because Open TimeStamps relies on Bitcoin for the truth of the
timestamps, the central third parties on a position to fake things.

*Peter McCormack:* Okay. So, I
wanna … I should’ve asked this at the start. I love asking this
question, ’cause it’s so simple. And, the first time I heard it was when
Epicenter asked Adam Berk, and it also blew my mind, just hearing it set
out. So, I’m just gonna ask you again. What is Bitcoin? The answers are
always different as well.

*Peter Todd:* Well, I’ll give you a
different answer.

*Peter McCormack:* Okay.

*Peter Todd:* Which is, Bitcoin is a
shared data structure, that we make artificially expensive to change, by
destroying energy every time we update it.

*Peter McCormack:* Yeah. I’ve
heard that one like four times. No. I’m joking. Yeah. I’m only joking.
Okay. Okay.

*Peter Todd:* Bitcoin is an
elephant, and it’s pink with like little spots.

*Peter McCormack:* I love the
energy angle. So, you’ve been around since the start, right? It’s 10
years and-

*Peter Todd:* Not quite.

*Peter McCormack:* Pretty much.

*Peter Todd:* I mean, I’ve known
about Bitcoin, since nearly the start. But, I actually got more active
into it a bit later. And, the reason is, I mean, relative to many other
developers, but the reason is because when I first learned about
Bitcoin, well, I’d just started a new job at a crazy startup. And then,
I was crazy enough to then also try to do a physics degree, while I was
at the startup. So, I didn’t exactly have a lot of free time.

*Peter McCormack:* But, I mean,
I’ve gone through the exercise of going through old mailing lists, and
old Bitcoin talk forums. And, there’s a number of names I recognise. A
number I don’t. And, I’ve seen you in there commenting and talking. So,
you were there like pretty much since the start.

*Peter Todd:* I mean, I started
working on this stuff full time 2014.

*Peter McCormack:* 2014.

*Peter Todd:* Which is a lot earlier
than many people.

*Peter McCormack:* But, having
been there, through the whole experience, how do you take it all in,
because even though you knew it would work, there’s a difference between
knowing theoretically it would work.

*Peter Todd:* Well, remember, I
thought it would work.

*Peter McCormack:* You thought
it would work?

*Peter Todd:* And then, I started
realising, hang on, this isn’t as good as it sounds.

*Peter McCormack:* Right. Okay.
We’re going to come back to those things. But, 10 years on is still
exists. It holds billions of dollars in value. At one point, hundreds of
billions. There is the talk of ETS. We have futures. We have so much
happened. Did you foresee all this?

*Peter Todd:* I mean to be perfectly
honest, this it doesn’t really surprise me that much. I mean, you always
gotta be a bit careful. I mean, your memory of what you thought five
years ago can be a bit vague. But, I don’t think if you’d asked me that
many years ago, would it? Could it get to where it is now? I would have
said no.

I think I would have said, “Yeah, I mean, this is plausible. It is an
obvious utility. Digital gold is obviously useful. So, if things don’t
fail and it continues to grow, I mean, surely could get to this point.”

I think the more interesting question is, well, how big could it get?
And, I would actually put relatively small limits on it. We’re not gonna
see … First time I bought Bitcoin, I bought it for 20 cents of a
Bitcoin.

*Peter McCormack:* Right.

*Peter Todd:* And, I tell you, that
was the best financial decision of my life. The worst financial decision
of my life was only buying $20 worth.

*Peter McCormack:* Hold on. What
is that? That’s like a hundred Bitcoin. Yeah. But, we won’t have
hindsight.

*Peter Todd:* But, the thing with
that is looking at how that grows. I mean, how many zeros is that times?
Call it 10000 times growth or whatever, depending on what price you
pick. We’re not going to get another 10000. The world economy is too
small for that. We’re not that far away from having more money in
Bitcoin than in the US dollar and gold combined.

Yeah. That’s if I remember correctly, it’s like a hundred X. That’s
pretty … That’s a lot smaller than 10000X.

*Peter McCormack:* Yeah. But,
I’m not convinced you care that much about price beyond the wider kind
of a PR [inaudible 00:12:17] and brings people into the system. I don’t
think you’re that. I don’t see you as somebody that is incentivised by
the price.

*Peter Todd:* Well, I mean price is
a funny thing, ’cause people often say, the price doesn’t matter. And,
that’s definitely not true. Bitcoin security model relies on it being
valuable. There is no getting around that. And, it probably would not
work, if the price was said a thousand times less. Someone would
probably attack it for kicks and giggles.

*Peter McCormack:* So, you were
saying you started to look at the reasons why it won’t work. What were
the main issues that you found, and where the things you attempted to
try and break?

*Peter Todd:* Well, really, like the
one big thing for me was when I realised, “Oh yeah. Scalability really
matters, and this stuff doesn’t scale.”

*Peter McCormack:* Right.

*Peter Todd:* I figured that out,
you kind of says embarrassingly late. But, in terms of like how long I
was looking at Bitcoin seriously, fairly early. From the time I started
looking at Bitcoin seriously, to when I realise this, and how important
it was, we’re probably talking like three or four months.

And, that was while I was at a startup, doing a university career at the
same time. Simple truth is, I just didn’t pay that much attention to it
for quite a few years. And, when I realised that, well, I got very
active and tried to solve this problem. And, also importantly got very
active in debating people who thought it wasn’t an issue.

*Peter McCormack:* So, were you
debating Rodger?

*Peter Todd:* Oh, he wasn’t around
but around then.

*Peter McCormack:* Like you were
going about earlier, okay. So, who would be debating this?

*Peter Todd:* Gavin Andresen, and
actually literally debating Gavin Andresen on Bitcoin talk forums was
probably the thing that got my name up there.

*Peter McCormack:* Right, okay.
Because-

*Peter Todd:* There is a thread on
Bitcoin talk where I disagree with Gavin Andresen, and it just
spiralled.

*Peter McCormack:* And what? The
disagreement was what? Block size?

*Peter Todd:* Exactly.

*Peter McCormack:* Okay. What
did he want?

*Peter Todd:* His viewpoint was,
yeah, he can … If I remember correctly, his exact viewpoint was you can
have an unlimited block size. And, that was just such an extreme
position. I laid out, very carefully, why this did not work. And, it
wasn’t the first time there’d been a disagreement on that, but at least
for me personally, that was the timeline when, “Hey, this is Peter Todd,
the guy who disagrees with Gavin Andresen on this. And, these seem are a
good point.

That’s really why my name got known. And, things just built on there.

*Peter McCormack:* But, there
are different reasons why … Well, people give different reasons for why
a larger block size won’t work. Some people I’ve heard discuss it
because it doesn’t scale in computer power, ’cause of nodes.

*Peter Todd:* Remember, the notes
Gavin’s view there was an unlimited block size. He thought the
incentives were such that miners would voluntarily restrict the size of
their blocks, even though they could make the biggest blocks if they
want. And, I laid out basically with a bit of math and game theory why
this is a bad idea.

That wasn’t even like a bigger picture. It’s just this is broken,
because miners can do this when they create a bigger block, they’re
going to push out the competitors. That’s kind of the arguments in a
nutshell. And, the simple reality was, I was right on that. And, that’s
just so well supported by academic research since. And, Gavin was just
dead wrong.

*Peter McCormack:* And, has he
ever come back and said, “You were right”?

*Peter Todd:* Nope.

*Peter McCormack:* Okay.

*Peter Todd:* I mean, there’s a
reason why he’s no longer involved in Bitcoin in any real sense. He just
wasn’t competent enough to do it.

*Peter McCormack:* Yeah. There’s
probably more than one reason as well, right?

*Peter Todd:* Supporting Craig
Wright was probably not the best move. But, all that stems from the fact
he just isn’t that competent at what he was doing.

*Peter McCormack:* And, I guess
it requires a certain level of competency to be able to work at that
level. And, it doesn’t feel like there’s a lot of people at that level.

*Peter Todd:* No, definitely not.
No. Most programmers in general, do you not have the capability to work
on this stuff, because they don’t think it adversarially. It’s a tough
thing for people to imagine. Most people are just not used to imagining,
“All right, what are the bad things that could happen?”

Whereas for whatever reason, I, and a few other people, are good at
that. I’m quite happy to imagine all the ways people could screw people
over.

*Peter McCormack:* What do you
make of Luke’s ideas around a smaller block? Is it 300K?

*Peter Todd:* I think his technical
arguments for that are good, but I think he doesn’t understand the
social side of that, which essentially makes it impossible. And after
all, I mean, let’s face it, Luke is a crazy evangelical Catholic. He has
very, very, very strong beliefs that are ultimately driven by very
strongly held principles.

He is, to us, an evangelical crazy Catholic. But, that comes from him
having very well defined beliefs and very strongly held principles. And,
the logical conclusion of that is his belief system.

And, I think what Luke … I’m not even sure I could say that he fails to
see, ’cause he may very well understand this perfectly, but you know why
Luke would say something like that is, he has the principles, and he
takes it to his conclusion. Whereas the way I’d put is, “Yeah. I mean,
he’s not wrong, but it just ain’t gonna happen.”

*Peter McCormack:* Right. Okay.
Where do you envisage the block size being in the future? Do you think
it was gonna stay as it is, or do you think at some point there’ll be a
change?

*Peter Todd:* Oh, I think it’s
plausible actually for the rest of life of Bitcoin, we’re not going to
see another block size increase. And, the reason why I say that’s
plausible is ultimately things lightning and whatnot work pretty well.
And, what would it be right now? Like 15 transactions per second or
something is actually a fair amount.

And, the way people use Bitcoin, like after all, for Bitcoins be wildly
successful, it doesn’t necessarily mean that people are actually making
payments on it. Bitcoin as a store of value can be an incredible success
story.

I think the bigger threat we would have is actually Bitcoin’s inflation
schedule, ’cause in the long run … And, this isn’t a short term thing,
but this is like 10, 20 years down in the future, there might not be
enough inflation to pay for security.

*Peter McCormack:* I just wrote
that down, actually. So, I’ve got a couple of questions about that. So,
if it’s just a store of value, and there wasn’t enough Bitcoin being
moved around for fees, and the mine of rewards have dropped, that’s a
huge risk for the security of Bitcoin, right?

*Peter Todd:* Absolutely.

*Peter McCormack:* And-

*Peter Todd:* But, that’s a risk
like 10, 20 years in the future. That is a very long time. And, by then,
who the hell knows what the risks are?

*Peter McCormack:* But Peter
Todd thinks adversarially, and I think that goes into the basket of
things that you probably are thinking about now.

*Peter Todd:* Yep. Well, let me look
this way. If I were able to go back in time, and redo Bitcoin, ’cause of
course, I am Satoshi as is everyone else.

*Peter McCormack:* I’ve read it.
I’ve read you invented Bitcoin at 12.

*Peter Todd:* Yeah, yeah. If I was
able to go back in time and create Bitcoin from scratch, I would have
made it have a perpetual say 0.5% or 1% inflation rate.

*Peter McCormack:* Okay. That’s
controversial, for some people.

*Peter Todd:* I’ll put it this way
if you can’t afford like a 0.1% or 0.5, or even a 1% inflation rate,
what the fuck are you doing with your life? It’s 1% a year. So what?

*Peter McCormack:* So, who have
you discussed that with? And, like you don’t have to name names. But,
have you discussed that with people? What’s the general reaction?
Because there’s no reason for that not to be introduced in the future,
right? I mean …

*Peter Todd:* I think the general
reaction is … Well, first of all, Bitcoin right now has what a 4%
inflation rate. We’re a long way from any of this discussion being
relevant. So, I think the general reaction right now is, it's pushing it
to the future. It’s just not a discussion worth having right now.

It’s drama, and of course, you look at my twitter account, and I don’t
shy away from that. But, most of the development community wouldn’t
really wanna touch the issue. And, I think they’re right. There is no
reason to touch this issue until it actually matters.

*Peter McCormack:* What about if
Lightning Network is hugely successful? And, people stop using the base
chain, because Lightning is fast, and it’s cheap, is instant. Could we
get to the point where there’s no argument to use the basechain, because
Lightning is as trusted as the base chain? Do you see what I’m getting
at?

*Peter Todd:* Well, I mean,
Lightning security model is riskier than the base chain. It just
doesn’t … Lightning, there’s a good reason to use it beyond scale. I
mean, Lightning has much better UI experience. But, the simple reality
is the Lightning security model is more dangerous than Bitcoin itself,
assuming that you’re able to wait for confirmations.

Under certain cases, Lightning can actually be much more secure. I mean,
if I go pay you with Lightning, the security of that payment from the
point of view of being reversed 10 seconds from now is far better than
the main chain ever could be. In effects, it will be better probably
what an hour or two into the future.

But overall, if you’re making big payments that aren’t time sensitive,
main chain has better security. On the other hand, this idea of
Lightning taking my transaction fees, that’s not unique to lightning.
Tons of things do this. Exchanges do this. Probably the most payment
volume that happens is actually on exchanges. Liquid side chain does
this as well. Liquid takes transaction fees away from the main chain.

There’s no end of things that take transaction fees away from the main
chain. And, the inflation arguments I would give is very simple. It’s,
well, make sure you always have this mechanism to ensure that the chain
keeps marching forward.

Even with transaction fees, you actually need this for a kind of subtle
to game theory technical reasons. The simple reality is, Bitcoin without
an inflation subsidy has a much worse security argument than Bitcoin
with an inflation subsidy, even if you have transaction fees paying for
things.

*Peter McCormack:* I haven’t
heard you talk about this a lot though, right? So, are you waiting? Is
it a case of priorities? Deal with what needs to be dealt with now? And,
you’ll bring this up in 10 years?

*Peter Todd:* Yeah. It’s just isn’t
relevant for literally like another 10 years or so.

*Peter McCormack:* What about
10-minute blocks across the solar system though? When is that going to
be a precedent? I read that.

*Peter Todd:* Well, yes. I did a
talk, actually. I believe the title of the talk was a solar powered
space miner. Yeah. Solar Powered Space Pirates, a Threat to Bitcoin.
And, the simple answer to that is yes, if space travel becomes cheap
enough that big mining operations are operating far enough away from
earth that the speed of light gets people out of consensus, yeah,
Bitcoin’s fucked, and we’ll probably have to increase the block control.

*Peter McCormack:* And, say are
you general evil?

*Peter Todd:* Yes, I’m a bad person
capable of love.

*Peter McCormack:* Okay. Outside
of Bitcoin, ’cause other Bitcoiners are very Maximalist in nature. But,
I have seen you talk about Zcash and a theory. Like, what’s your
position on alternative coins and alternative currencies?

*Peter Todd:* Well, the thing is,
I’m not a Bitcoin Maximalist. I’m a Maximalist. Anyone who understands
economics and finance, and how markets work will be a Maximalist because
it is more efficient to have one currency than a whole bunch of
different ones. That’s just not a controversial opinion. And, it’s a
controversial opinion amongst scammers who want you to go by their ICO.

But, standard non-scam driven, economic thinking, this is not a
controversial opinion. This is how the Euro got created. And, there are
certainly downsides to not having multiple currencies. The one world
currency thing has a lot of very real economic problems. But, they’re
not problems that apply to things like Bitcoin.

For digital payments in a decentralised environment, it’s just natural
to end up with one coin. Whether or not it’s actually Bitcoin, who the
heck knows? But, Bitcoin’s technical design and sort of technical ethos
currently are definitely the most suitable for being the one currency
everyone uses.

That’s just a matter of like simplicity, reliability, of disinterest in
making deep dangerous changes. And, there’s just … Conservatism is a
good thing for that store of value. It’s just a pretty obvious set of
combinations that mean Bitcoin’s kind of the default there.

*Peter McCormack:* But
therefore, is it good to have competing alternative currencies?

*Peter Todd:* I mean, it’s not going
to hurt things. But, for the most part, the competing alternative
currencies are scams.

*Peter McCormack:* Every single
one?

*Peter Todd:* Well, some are more
scammy than others.

*Peter McCormack:* Is Ethereum a
scam?

*Peter Todd:* Ethereum is a funny
example, because the way it was launched, and the way it was promoted,
that’s much more of a scam than any of the surf currency itself. Had
Ethereum, for instance, been launched. I mean, it’s hard to kind of come
up with an example of where this would be possible.

Let’s suppose, hypothetically, somehow launch Ethereum, where it was
just an add on to Bitcoin, where somehow the people behind Ethereum were
making money off of it. This isn’t really technically feasible, but
let’s assume for the sake of argument was. It would still wind up being
a scam, even without a separate currency, because they were advertising
things that they knew would not be possible.

Ethereum is just a bed of lies if you will. And, I think it’s very
unfortunate, ’cause it also means a lot of academics, because they can
get grant money from this, and because Ethereum is easy to experiment
on. I think it’s pulled down ethical standards of academia.

And, it’s just an unfortunate position to be in. And, this is also … I
mean, maybe a good way to explain this is the private chain side of
things. Well, some of that’s perfectly reasonable. A lot of the more
grandiose claims made are effectively scams. And, it’s sort of a new
interesting category of scam where it’s not like we’re directly ripping
people off, but rather were lying about what our products can actually
do, and we’re getting away with it because it’s security.

And, in security, well I can sell you a magical rock that keeps lions
away. How do you know it doesn’t work? There are no lions around.

*Peter McCormack:* So, what are
the main claims for Ethereum then that you think of false?

*Peter Todd:* I mean, it’s a funny
one, ’cause it’s tough to pin down because the main claims were designed
to be vague. Claims like this is a world … A great example is the world
computer thing. What does that actually mean?

When you start thinking about any reasonable interpretation of it is,
no, this is total bullshit. But, it’s presented in a way which is vague
enough, it’s tough to argue against. You’ve got to play pin people down
on what does a world computer mean? What’s it actually computing?

Now, you ask a normal person, I think, “Oh yeah, computations done
somehow on Ethereum.” And, it’s no, that’s not how it works at all. Your
Ethereum node redoes the computation. It’s not a computer, it’s a
verifier, whereas the sort of general way of building consensus
applications I push is client-side verification, which is quite
explicit.

Yes, we have this big dataset that your computer verifies. And, other
people don’t even have to verify the data. They don’t even necessarily
know what it means. They may never even have a copy of it. But, if I
want to convince you that something’s true, like I just sold you a
house, I give you the data to prove it’s true, and you verify that data
yourself, and you come to a conclusion that yes, you now own a house, or
no, I’m trying to defraud you.

That is a sane way to talk about block chains. A world computer is not.
A world computer is a pie in the sky scam material. And, even Vitalik, I
mean he’s kind of admitted, “Well, the world computer stuff was a bit of
a red herring.” I’m sorry. The moment you say red herring, and please go
and invest in my thing, you’re probably scamming someone.

*Peter McCormack:* I don’t get
the feeling he intentionally scammed somebody.

*Peter Todd:* You know about his
quantum computing thing?

*Peter McCormack:* No, tell me.

*Peter Todd:* Well, just prior to
Ethereum, he was involved in a quantum computing scam.

*Peter McCormack:* Okay.

*Peter Todd:* And, essentially what
the scam was was they would do simulated quantum computing that would
somehow be better than anything else. It just didn’t make any sense.
And, his claim is, “Oh! I kind of young, and just had higher hopes for
it. That’s all.” No, you weren’t that stupid.

First of all, you were like 19, at university. You knew what this was.
You knew this was bullshit. Yeah. The guy’s got the mind of a scammer,
basically. He’s got the intentions of a scammer.

He’s very clever about it. He’s not someone who is careless. He’s not
someone who gets himself clearly involved in a scam in the way that you
can prosecute. But, he’s pushing dishonest stuff. I mean, that’s what
scammers do.

*Peter McCormack:* So, ETH 2.0,
I’m guessing you’ve read some of the specs.

*Peter Todd:* I mean, it’s one of
those things where he just go put up a whole bunch of complex shit on
the wall to try to be resistant to criticism. I think I believe Greg
Maxwell was the one who deserves credit for this. But, he’s pointed out
how the general approach of Ethereum crowd is, they put something out,
it gets shot down because it doesn’t work. So, rather than go back and
fix the problems, they make it more complex.

And, if you keep repeating this, eventually you appear to be secure, not
because you’ve actually created something secure, but rather, you’ve
created something sufficiently complex, it’s just too much work to
criticise.

*Peter McCormack:* Yeah. I mean,
I’ve read James Press, which is medium posts recently looking at ETH
2.0. I don’t know if you saw it.

*Peter Todd:* I might have.

*Peter McCormack:* I mean, the
only thing I could think of when I was reading this is, “This just seems
an insanely complicated way of creating a distributed database.” I was
written about sharding, and then I was reading about state rent, and
that certain things would be on chains. And, I was just thinking,
“What’s this for?” I just can’t get my head around it.

*Peter Todd:* It is designed to be
sufficiently complex that you can’t criticise it. Now, on the other
hand, if I wanted to explain to you how Open TimeStamps works, I could
do that in a morning, including the part where I explain how hash
functions work. It is dead simple.

If I wanna explain to you how my proof Marshall Project works, I’d
probably have to go spend the afternoon as well. This stuff is designed
to be dead simple. I mean, this is why, on my twitter profile for a long
time, the pinned tweet was, “A blockchain is a chain of blocks.”

*Peter McCormack:* I knew that
was coming.

*Peter Todd:* Yeah. Blockchains are
not complex things. People try to make them complex things, so they can
go sell stuff, or in the case of academic skill, write papers and make
them relevant. But, they just aren’t that complex.

*Peter McCormack:* Yup. And,
they have one purpose. Like, Jimmy talks about this a lot. The
blockchain has a really good purpose for Bitcoin and money. Nothing else
really. And, I’ve tried-

*Peter Todd:* I actually disagree on
that.

*Peter McCormack:* Well, that’s
good, because I’ve tried to be open-minded, and tried to kind of just be
as open-minded as a can say, “Okay. Is there something else here?” Like-

*Peter Todd:* You’ve gotta remember
because I define a blockchain is a chain of blocks, I would actually
have the viewpoint that, “Yeah. Blockchains are worth adding basically
anything.” I mean, the moment you have a data structure, where you even
wanna create a backup of it, it might as well throw it blockchain in
there so it can update and ensure you have a complete copy.

My Open TimeStamps project, it’s a centralised system that creates
timestamps, long story short. Well, one issue with it is if the central
servers go down, you want to have a backup of all the timestamp proofs
they made. How do you make that backup? Well, currently, you go and go
through this HTTP, RPC, restful protocol, total box standard stuff, and
he just download one after another.

How do you know that your copy of the back up is the same as mine? Well,
obviously you gonna add hashing to it. Well, how are you going to add
hashing to it? Well, why don’t you go and make updates, and have one
update hash another? Oh, what do you know? We’ve created a blockchain.

*Peter McCormack:* Indeed a
blockchain, yeah. Okay. So, I met with Zac Prince of Block Fight, and we
have a long chat about Bitcoin. They do crypto back loans. And, it’s a
market that makes sense. But, he also said, it doesn’t make sense when
they’re Lending money, say to Argentina, that if you’ve got to lend out
Bitcoin because it’s volatile.

He said it makes sense to do a stablecoin. A stablecoin is built on
Ethereum. So, whether it’s a scam or not, the fact that people are
building things that people are using, how do you sit with that?

*Peter Todd:* Well, so the point I’d
make there is, the stable coin’s built on top of Ethereum. From a tech
perspective, that could actually be the right decision. And, the reason
why there can be the right decision is, yeah, I mean the infrastructure
is there. We know we can throw together something. It doesn’t work as
well as it could. But, the tooling’s there, we can get it done, push it
out the door.

I’ve literally told clients of mine, “Well, you actually might want to
build this on Ethereum, ’cause alternatives don’t exist yet.” We know
they can exist, but the effort to actually make it work hasn’t been done
yet. And, in all equally, I’d say the stable coin idea is just an
obvious no brainer.

You might want to have exposure to this currency. Why wouldn’t you want
to have some nice digital way of doing it with a well-defined trust
relationship? It’s just not a complex thing to talk about. It has very
obvious reasons to, in much the same way like having an ETF, it makes a
lot of sense for certain people.

Now, having an algorithmic stable coin, where you try to do consensus,
decentralised magic to keep the price stable, there’s a pretty good
reason. I think those are impossible. It’ll never work.

But, a trusted stable coin, where you have a central issuer, who you
have legal mechanisms to ensure that you get your money back, yeah. I
mean, why not? Hell, in some cases, a stable coin that’s actually a
total fraud can actually make sense. If I’m a trader, and I want to
temporarily move out of a position into a stable thing, and then move
into another position, even if the stable coin is a total fraud, and
there’s no US dollars or whatever backing it, it can still be useful for
me as a trader, because my risk of the stable coin going belly up, and
the fraud playing out maybe less than the risk I have of not moving my
currency, not moving my assets into that stable currency for whatever
reason I needed to.

*Peter McCormack:* I only see
the two use cases. I see Bitcoin and a stable coin. That to me is pretty
much all I think we need, personally. I mean, you probably can think of
some great other examples.

*Peter Todd:* Well, if you’re
talking about money, and things related to money, I think you’re a lot
more right than people would want you to be.

*Peter McCormack:* Yeah. Well,
do you know why? Because other people want to invent other uses for
blockchain, ’cause they want to monetise it. And, other people want to
shoot down stablecoin-

*Peter Todd:* So, I guess the way
I’d put it is, if there’s a money component involved, I think you’re
ultimately right. If there’s not a money component involved, and we’re
just trying to do something related to some asset or some data
structure, which for a reason we what consensus over, I mean, yeah,
block chains basically always make sense.

But, that’s because of blockchain is just a chain of blocks. It is not
rocket science. I mean, I love the example GET. People say, “Oh, but
then is GET a blockchain?” And, my answer is, well yeah. it’s basically
a blockchain. It doesn’t quite precisely match the linear chain of
blocks in how we use it. But, why GET is a set of hashed things in a
direct acyclic graph is essentially the same reason why Bitcoin is a
chain of blocks.

I want to make sure that my copy of the source code on my computer is
the same as your copy. That’s why Bitcoin is blockchain. That’s why GET
has something nearly a blockchain.

*Peter McCormack:* What about
privacy coins? Obviously, I’ll see you tool more about Zcash than-

*Peter Todd:* Say proof of what?

*Peter McCormack:* Privacy
coins.

*Peter Todd:* Oh, privacy coins?

*Peter McCormack:* Yeah. So,
I’ve seen you talk about Zcash more than, say, Monero. What’s your
position on privacy coins?

*Peter Todd:* I mean, they make a
lot of sense if they work. The only reason I want to talk more about
Zcash that Monero is Monero has less wrong with it.

*Peter McCormack:* Okay.

*Peter Todd:* Monero definitely
could, in theory, have less privacy than Zcash. The underlying idea of
what Monero is, it certainly has the potential for less privacy than
Zcash. But, the Monero people have just done a competent job
implementing something with very little drama, and the people behind it
all seem pretty ethical. And, there’s very little criticised about
Monero.

*Peter McCormack:* It’s the only
other crypto I hold. I’ve got Bitcoin and Monero.

*Peter Todd:* Yeah. I mean, I hold
essentially trivial quantities of Monero and Zcash, enough to use on
occasion. But, in theory, Zcash should be better. Its privacy, the
potential for privacy’s much better.

*Peter McCormack:* Is that
’cause it uses Zcash nodes?

*Peter Todd:* Exactly. Yeah. The
difference is, in Monero, your payments might’ve come from immediately
one of say 10 different people, and then of course you know a hundred
and so on, whereas in Zcash, the moment you do a payment, if it’s a
shielded payment, you’re now part of this big anonymity set.

What’s wrong with Zcash is sort of all the implementation details and
sort of the people behind it.

*Peter McCormack:* Wow! So, I
interviewed Zooko last week. And, one of the most important questions I
think I put to him is I said, “Is a Zcash a company?” ’Cause that’s what
it feels like. It feels like it’s a company.

*Peter Todd:* Yeah, it is,
effectively. And, the reality is the way they do … The way they will do
Zcash is very explicitly centralised. And, they kind of try to put fake
leaves on edge. But, probably it’s a company of a few different people
with really dubious ethics. It’s just …

I mean, it’s kind of fortunate, ’cause it’s a scary thing to have. The
best privacy tech out there, for that type of use case, run by people
who will lie to you.

*Peter McCormack:* Yeah. And,
I’m not surprised that it seems like [inaudible 00:38:40] brothers have
a preference to Zcash. It didn’t surprise me.

*Peter Todd:* Yeah. Well, the thing
I think with it is, people in that kind of sphere, they would rather
work with people who are not totally ethical. I get the sense this is
why Coinbase and Zcash kind of seemed to get along, because they kind of
see eye to eye on, “Well, we’re not going to strictly tell everyone
exactly how this really works. We’re happy to Futz with stuff.”

I mean, when they did the trustee set up. The simple reality is they
botched it. And, rather than just come and say, “Look, here’s where we
made our mistakes. Here’s what we’re going to do better.” They just
lied. They said it was multiparty set up in. And, the reality is, it
wasn’t.

It was intended to be, but due to technical failures, I don’t think you
can make that claim. In the Bitcoin world, I think had that happened
with the people behind Bitcoin, they would have said, “Look, we screwed
up this, this, and this. We’re going to fix this next time. Here’s the
timeline where we roughly wanna do it. Here’s why this isn’t necessarily
a big deal, et Cetera, et cetera.”

Had Zcash has simply done that, I think Zcash would still be a success.
But, that’s not the way they think. They think, “Well, shit, we got to
have good PR on this. We’ve got to preserve our money coming in.” And,
after all, I mean, they get a ton of money from Zcash. They have
incentives to hide flaws, because that’s her income, whereas in the more
long term view, would be, “Well, all right, we might lose some money in
the meantime, while we lose some market confidence. But, the longterm
effect will be people will actually trust us.”

I don’t trust Zooko not to lie me.

*Peter McCormack:* Yeah. I’ve
got to say, I trust Ricardo a bit more.

*Peter Todd:* Yeah.

*Peter McCormack:* You’re a big
fan of Ripple Coin, right?

*Peter Todd:* Well, I think Ripple’s
wonderful idea. You mean Ripple, the original concept to like peer to
peer payments, right?

*Peter McCormack:* I’m on about
Ripple Coin.

*Peter Todd:* Yeah. That’s
remarkably scammy.

*Peter McCormack:* Yeah.

*Peter Todd:* It’s interesting. So,
I, at one point, worked for R3. And, I should be careful what I say
here, cause there’s probably NDAs, and they’re a bit … They are not very
happy with me. But, long story short, I think what I can say is, initial
was working as a consultant, evaluating other coins, and other systems.
And, I think their business plan there was let’s just go buy something
and let’s package it up and sell it to banks. A perfectly reasonable
thing to do, act as middlemen.

Well, they had me analyse Ripple, ’cause at the time, there was a lot of
interest among banks. And, I analyse it, and said, “Yeah, the
centralised system obviously.” Which isn’t necessarily a bad thing. For
banks, I think, that would have been fine.

Of course, I soon found out, they weren’t saying it was centralised
banks. They were just flat out lying about what it actually was. So,
when I did a big presentation in front of most of the world’s major
banks and representatives from them, they’re like, “Wait, Ripple’s
what?” ’cause they’d been lied to.

And, ripple these days, I don’t actually get the sense that’s true
anymore. I get the sense that Ripple, the company, has become much more
reasonable. But, Ripple’s tied to currency, and they don’t have any
ability to get rid of this currency, which doesn’t really … It isn’t
needed for technical reasons.

So, I think they’re putting in a very awkward position where there’s
rabid fan base of big holders, essentially.

*Peter McCormack:* Very strange
group.

*Peter Todd:* Yeah. Very, very
strange. And, I would not be surprised if … Like as an example in
Twitter, you say something about Ripple and the XRP troll army comes
down on you. I would not be surprised if, for the most part, that sort
of army of crazy people is actually not that involved with Ripple, the
company selling things to banks. I don’t think that that dumb.

But, they can get away with it. There’s no mechanism for Ripple, the
company, to actually extract themselves from the currency. Like it or
not, they created the currency. They own a big chunk of it. They can’t
get away from that. And, I mean this is one of the real dangers of
creating coins for services. You might get tied to a coin that’s
pointless.

*Peter McCormack:* Well, that’s
why I call it Ripple Coin. I never changed from Ripple Coin, because I
think it’s important for people … It was like with Bitcoin cash becoming
BitCash. The alternative name, I think, was important.

I always call it a Ripple Coin, because I think people have to know,
they have to know, it was created by the company. That it wasn’t a gift.

*Peter Todd:* I mean, it’s worse
than that. I mean, last I checked in government, I haven’t looked very
recently, the consensus was still controlled by the Ripple company. You
can’t get away from the fact Ripple’s architecture is centralised.

The XRP community can say all they want. “Oh, all you know, it’s just
nodes. You can go pick a different set.” Well, yeah. I mean, I can go
pick a different currency. Unless you and I agree on the same set of
nodes, the reality is we’re not looking at the same currency. And, that
was really all my paper was.

I just pointed out. Yeah. Obviously, if you pick a different set of
central nodes controlling the consensus than me, we can get out of
consensus, and all hell will break loose. Thus, the only sane thing to
do is pick the same set of servers for control of consensus.

*Peter McCormack:* One thing I
do want to ask you about is because I think one thing, a lot of other
alternative currencies have managed to do, whether it’s right or wrong,
but by design have been able to create an incentive structure and
financial incentives for developers.

Bitcoin is still largely voluntary, or there are some contributions in
different ways. I know you’ve had a contribution. But, it’s-

*Peter Todd:* My point is not
voluntary in the sense that developers go unpaid. It’s voluntary in the
sense that the currency itself isn’t directly paying developers.

*Peter McCormack:* Of course,
yeah.

*Peter Todd:* But, the reality is
there’s enough money floating around for developers get paid, even total
screw ups like me.

*Peter McCormack:* Are you still
working on Bitcoin?

*Peter Todd:* I’m not working on
Bitcoin core. But, I am working on projects around it like Open
TimeStamps and Proof Marshall. And, I’ve had surprisingly good success
getting paid for that.

*Peter McCormack:* I guess it
depends on who you are though. And, the reputation you’ve built, you can
be funded. But, when you say there is funds available for developers, I
mean, how do they go about receiving funds? How do they do it?

*Peter Todd:* I mean, it’s kind of
like anything. You do a bit of work, you show that you’re competent, and
you find someone who’s interested in paying you to do more work. If
you’re competent, and you prove that, the simple reality is there are
ways to go get money. It is not the hardest part.

The hardest part is getting to the point where you’re confident. And,
the things that us, even in coins which have developer funds, getting
money out of those developer funds is surprisingly hard.

*Peter McCormack:* Right, okay.

*Peter Todd:* Like Zcash is a great
example where the Windows clients for Zcash we’re completely
unmaintained because Zcash wasn’t giving them any money.

*Peter McCormack:* Okay. So,
’cause I sort of say would Luke put up his patron, and I supported them.
It just feels like there should be almost like something he shouldn’t
have to worry about.

*Peter Todd:* How? I mean, the
simple reality is, having funds in these coins is not a magic solution
to that either. Yeah. The bigger problem is more you getting to a
position where you’re doing interesting work that’s getting valued. And,
if you’re able to do that, and actually contribute, getting that money
is not that hard.

*Peter McCormack:* Is there
enough developers coming through? ’Cause we talked earlier about enough
of the kind of biggest and brightest minds who can really think
adversarially or think outside the box. But, are there enough developers
coming through who can we just work on more simpler tasks?

*Peter Todd:* The impression I get
is mostly yes. But, the interesting thing about this is like Bitcoin
core itself, that actual core software, I may not be very popular saying
this, but I think it’s true that they’ve got good enough developers,
maybe a little too many.

Bitcoin core itself doesn’t necessarily need to change that much. And,
it can change on a somewhat slower basis than it has. I mean, it’s not
really a big concern. The more interesting thing is like all the
periphery infrastructure around it. Things like libraries that actually
work are well documented and so on.

And, that’s not very sexy work. So, that may actually be the thing where
we need more money put into. But, when you look at other coins, which
should do over funds, they don’t do a good job with this either. So,
it’s not like this is a magic solution that’s proven to work. This seems
to be more a solution which has proven to make the people founded the
coin a ton of money.

*Peter McCormack:* Yeah. I spoke
to Brian Bishop. And, I think he says something along the lines of, “It
would be great if some parts of the cost start to become
compartmentalised, ’cause it’s kind of a big sprawling mess right now.”
Is that correct?

*Peter Todd:* Oh, yeah, yeah. The
fundamental like Bitcoin core architecture is not, I think, how you
would do it these days. I think in the context of when it was created,
it was probably the right decision to make. Do this very simple thing,
which one person can create, and one person can comprehend, and it’s
just one code base that’s very easy to review. But, for what we want it
to do now, it’s probably not ideal.

On the other hand, I mean, people often think, “Oh! Bitcoin core doesn’t
have this feature. It’s terrible.” Well, so what? Just turn on Bitcoin
core node, grab the data from it and do whatever you need to do. What do
you need to do? Do you need to have an index of transactions? Just
follow the blocks and index your transactions. It’s slightly less
efficient. But, so what?

*Peter McCormack:* Even if
people who kind of want the base change essentially ossified. Is that
the word they use?

*Peter Todd:* Base protocol is
pretty stable. Not quite as stable as say TCP/IP. But, it’s reasonably
stable. And, equally, so has the stability of TCP/IP held back the
Internet. I don’t think you’d make the case at all. If anything it’s
helped it by having the simple thing that works, and you can build on
top of it.

*Peter McCormack:* I wanna ask
you a bit about the work you’ve been doing. But, before that just one
kind of … I’ll say one final question. I haven’t got through hardly
anything here. This has been great. But, I do want to ask you about your
views on fungibility, because in doing my interviews, I’ve kind of had
two different perspectives.

There are some people who do want fungibility on the base chain. But,
there are some like Saifedean wouldn’t. Saif’s view is that we want to
say a completely transparent based chain, so we can ensure nobody is
operating with say, fractional reserves. Where do you sit in that kind
of field?

*Peter Todd:* I think his viewpoint
is technically ignorant there. You can definitely have … I mean, as an
example, ideally, Zcash would be completely non-transparent. In reality,
it’s nearly entirely transparent, ’cause you’re actually using the
shielded transaction features is hard and discouraged.

But, in theory, Zcash could be completely shielded. And, even then, it’d
still be easy to be transparent. The better argument to make there is
all the technology for privacy on base chains is potentially dangerous.

*Peter McCormack:* Okay.

*Peter Todd:* Yeah. Example being,
with Zcash, you have that trusted set up. A trusted setup could easily
fail. Implementation bugs could easily cause it to fail. In fact, the
fundamental Zcash library, the thing that verifies transactions, just
prior to release, they found a bug in it that could have allowed a
moment of inflation. And, that’s not even like a trusted set up failure.
It’s just a simple bug in it.

And, it’s not an easy bug to find. You really got understand math in
very deep detailed find something like that, because you’re relying
completely on the math to protect you from inflation. Whereas in Bitcoin
you’re relying on stuff you could explain to a drunk art student.
Speaking about a fine arts degree.

So, I’m a little bias there. I liked this level. But, that’s useful,
’cause it means tons of eyes can see this stuff. When Bitcoin had this
some recent inflation exploit-

*Peter McCormack:* CV bug.

*Peter Todd:* Yeah. Had that
actually being used, chances are alarm bells would have gone off in tons
of places, because people are looking at, doing the math, figuring out
how many Bitcoins are in existence. Does this number make sense? Any
idiot can do that. It’s not hard. For Zcash to do that, you need to
re-implement all Zcash nodes. And, it is a nightmare.

*Peter McCormack:* So, I guess
you’re keen on some form of fungibility, but do you … Are you keen on
it, say as a side chain or some kind? Like how do you-

*Peter Todd:* Well, I mean,
Lightning adds that. Any add on to Bitcoin that’s scalable will
naturally have better fungibility. And, the reason is, to scale, you
have to distribute less data to less people. It’s just not possible to
create a scaling solution that doesn’t at least add privacy to some
adversary.

As an example, Coinbase. Let’s suppose, well, PayPal. Let’s go really
out there. PayPal, compared to Bitcoin, has better privacy against most
adversaries. If I pay someone with PayPal, North Korean spies don’t know
what I did.

Obviously, the US government probably has a full copy of everything.
But, most of my adversaries now do you not know that I made that
payment, and have no way of knowing. That is categorically better than
Bitcoin from that narrow perspective.

If my adversary’s US government, totally different discussion. But,
PayPal scales. And, the only way it could scale is by reducing the data
available to the bad guys.

*Peter McCormack:* Okay. All
right. Look, we’ve done a lot here, but I do want to cover some of your
work. So, when I spoke to Jack Ma, he was like, “Peter’s really busy
working on Proof Marshall.” I don’t know anything about it. Can you tell
me, what is Proof Marshall?

*Peter Todd:* Well, all right. So,
first of all, my simpler project is Open TimeStamps. And, Open
TimeStamps proves data existed in the past. The problem with Open
TimeStamps is it doesn’t prove anything about whether conflicting data
also existed. An example being, I sell your house. I give you a sign
digital document saying, “I, owner of 1234 Main Street sell it to you.”

What you don’t know is if I already sold that someone else. Proof
Marshall fixes that problem by … It’s a library to create data
structures where you have consensus over. And, what consensus means
there is simply, in the definition of selling a house, all the possible
places where I could have put that data, you now can see. Thus, you can
rule out me selling the house to someone else.

And, how do you do that? Well, you throw in a whole bunch of Merkle
trees and hashing. This is … I mean, what’s hard about Proof Marshall is
that the strategy for the implementation is effectively taking pointers
and abstracting that concert.

Pointers are such a low-level fundamental idea in computer science that
just … The low-level mechanics of actually implementing this is
challenging and tricky to do well. And, you get a lot of issues. Like,
if I’m giving you a math proof that now you own this house, I want to
make sure that even if the code or writing that application isn’t that
careful, that math proof won’t, for instance, use up all the memory in
your system.

Turns out that’s actually a hard problem. It’s not a hard problem for
like Bitcoin level reasons. And, this is an economics problem. It’s
just, it’s a tough thing to implement at a computer science level, or
maybe I’m just not a very good coder.

*Peter McCormack:* So, what’s
your status? Where are you at with the project?

*Peter Todd:* About two weeks, for
sure.

*Peter McCormack:* All right. Is
that this week?

*Peter Todd:* No. I mean,
truthfully, it’s something where I’m always thinking, “All right, I
could finish this in two months.” But, two months later I say, “Oh,
yeah. I didn’t realise but this isn’t this.”

I mean, as an example, the first version I had, for how it would
represent, how it would obstruct a pointer, made the assumption that you
always hash the data. And, I did a bunch of work in that, and I was,
“Oh, yeah. That doesn’t actually work. That causes other technical
problems that, long story short, this doesn’t work.”

Another example was I had this … My most recent implementation had a
thing where when you took the data, in processing, and deserialised it,
you would make a copy of it. And, I naively thought, “Oh, that’s not big
deal. Make a copy of it. It’s all well, and good.” Of course, I go
through the adversarial think, I was, “Oh, shoot. Because I made a copy
of this, now my API doesn’t have a good way of assuring I don’t run out
of RAM, ’cause all of these extra copies.”

So, I had to effectively redesign it so that all the data can be
operated on directly. If you’re a programmer, the term I would say is
the serialised version of it is identical to what you would process in
main memory. Thus, you don’t have to make a copy to process it.

And, this is all like very much in the weak technical stuff. But, to
make a robust implementation that works well, you have to solve these
problems. And, it’s just hard. And, because it’s still at such a
fundamental level of design, having two people work on it once, it’s
very challenging.

*Peter McCormack:* Okay.

*Peter Todd:* ’Cause if I make a
change, I’m usually changing how any of the code works. And now, if I
have a partner working with me, suddenly everything they’re doing is
broken. Maybe if I was sitting next to a guy in an office, this might go
faster. But, it’s just not there. And-

*Peter McCormack:* It’s a
one-man project.

*Peter Todd:* Yeah, yeah. For now.
But, if it works, it’ll eventually work, and long store short is it’ll
be a nice library to write consensus applications, to do all kinds of
things you want. As an example, you could even implement GET and Proof
Marshall to just have a good way of making sure you and I have the same
copy code. Certificate Transparency is another example.

When you go to a website, the certificate that proves your talking to
the computer you think you’re talking to, like your bank, for instance,
that are published in a blockchain. The people who create certificate
transparency, of course, hate the term blockchain and probably would
strangle me if I said this in front of them. But, the reality is the
data structure is effectively blockchain.

In proof Marshall, you could do things like that and … All right. You
can do them now, but it’s just a lot less work when you have a library
that just does it for you. It’s like … I mean, SQL databases are like
this.

Sure. Prior to dimension SQL, you could, in theory, do anything you do
with. It was just so much more work to get there.

*Peter McCormack:* I think I’ve
kept up with about a good 50% of today.

*Peter Todd:* Well, it’s enough to
do a 51% attack.

*Peter McCormack:* Well, yeah. I
do wanna do that. I wanna 51% attack. We’re just going to have to do
another one another day, ’cause there’s so much more wants to talk to
you about. But, there is a couple of final closing things I want to talk
to you about. One is just a bit left field.

I’ve noticed you tweet quite a bit about journalism. Why does that get
to you so much?

*Peter Todd:* I think this really
comes down to … And, I’ll say straight off, this is an example of not
staying in your lane. This kind of phrase going around, stay in your
lane, only talk about the stuff that you’re supposed to do
professionally, and so on. And, I really don’t care what that for
Twitter.

And, a lot of that gets down to, what does it take to have a society of
the functions? You have to have people agree on basic facts around the
world. And, I think the reason why I’m critical of that, same reason
ultimately I’m critical of many scams in the crypto world, where people
were saying things, but the projects just aren’t true, and polluting the
ecosystem of ideas with false things.

And, unfortunately right now, we have a big problem with journalism
where, first of all, it’s not very fun. It’s not well funded. It just
isn’t that money to actually pay journalists to do their job properly.

I have quite a few friends who are journalists, and I see this every
day. I mean, the timelines they have to operate on are ridiculous.
There’s no way for them to do a good job given how fast they have to put
out articles with how little help. And, on top of this to make money,
you wind up with all kinds of dark practices, like clickbait.

And, when you combine that with the very ugly political landscape of the
US, you get really ugly things like Covington, where I think it’s pretty
fair to say major media organisation are, “Oh, this is a great story.
Fits our narratives really well. We’re going to get a ton of clicks on
this. Let’s rush published before anyone else does.”

And, the rush to publish is a really big deal. I’ve been told, directly
by people managing media organisations in the crypto space, that
collectively people like me are a huge competitor to them, because I can
tweet faster than they can publish, and literally minutes matter in this
stuff. If they’re not first to publish, they will get less clicks, less
views, less money.

It sounds so stupid, but this is the truth of it. And, that pushes a
cycle that just doesn’t allow for good research and good work. And,
unfortunately, there are no easy ways to stop this. Maybe one of the
solutions could be more use of defamation laws, and life moves on. But,
there are very like very, very real risks to this for freedom of speech.

*Peter McCormack:* Yeah. I mean,
my last interview that went out yesterday was Andrew Torba from Gab.com.
What do you think of Gab? I mean, the content is tasteless. But, do you
agree that …

*Peter Todd:* I’ve never actually
looked at Gab’s website itself. And, I’m kind of sympathetic to them. I
mean, I think organisations like that should be able to exist. I think
the fact that they’ve been deplatformed from payment providers is a
straight up antitrust issue. And, they’re not the only example of this.

I mean, the fact of the matter is companies like PayPal, MasterCard,
Visa, are able to restrict freedom of speech very effectively. Not as
effectively as they could without safe things like Bitcoin. But, the
amount of control they have over what content gets produced is very
scary.

Where deplatforming ends up is people being able to restrict speech,
because they can say, “I don’t like what you’re publishing, and we’re
going to cut off your money.” And, you can’t, for instance, do
journalism without access to a flow of money to go pay people to do
stuff.

And, this is a very, very real issue. What Patreon has done is scary.
Now, as a libertarian, I’d say Patreon itself, I don’t have issues with
them cutting off people. What I have issues with are the payment
providers who have now said, “Oh, you’re trying to compete with Patreon,
we’re going to cut you off as well.”

That’s where I think this crosses the line. It’s getting very scary as a
society. So again, do I support Gab itself? Whatever. Let them do what
they want. But, do I support fighting back at why Gab has a hard time
running a business. That’s what matters to me.

And, I’m just not that concerned about people spreading hate on the
Internet. I don’t think that’s actually a big concern for society.
Particularly when we go see the left’s doing exactly the same thing but
in a different context. There’s no like clear moral high ground here.
And, obviously, if the left can do this, and society hasn’t collapsed,
it’s not necessarily such a bad thing.

And, in some ways that kind of thing pisses me off more ’cause I
definitely identify as liberal.

*Peter McCormack:* Well, yes I
do sometimes. But, I was saying to Andrew that like politically, I’ve
got no idea anymore where I am, because I’m finding so much to dislike
about everyone. But also, there are these certain conservative things I
do like, and then there’s a kind of liberal things I like. And, I’m just
so confused. I don’t know where to position myself.

*Peter Todd:* I mean my entire adult
life … I live in Canada. My entire adult life I’ve voted for the Liberal
Party, which in Canada, the Liberal Party’s what the name suggests. It’s
the Liberal Party.

These days I’m not sure I identify with them anymore. I’ll probably
still go on voting for them because they’re the best of bad options.
But, yeah. And, I think part of it too is like many of the social issues
I do care about. Like freedom of speech, and gay rights and so on. A lot
of that’s actually kind of solved.

Abortion’s legal in a lot of places. Gay Marriage is legal. The things
that I cared about, we solve those problems.

*Peter McCormack:* Through free
speech.

*Peter Todd:* I mean just through
like the way politics moved. The Conservative party’s eventually, “All
right, fine. We’ll go along with this.” And then, probably isn’t … At
least in Canada, it’s probably not going to get reversed. So, now it’s
like, “Oh, do I need to go vote for liberals again? I mean, the things
that we’re fighting for gut solve, the things that they’re now fighting
for, I don’t agree with. It’s a very strange situation to be in.

*Peter McCormack:* I think we
could do a whole show on this. All right. Just to close out. We’ve had
10 years of Bitcoin. So, we look back. Looking forward over the next 10
years, what are the key things you would like to see happen? And, what
are the most important things, not just in terms of code and develop it,
but just overall for Bitcoin? What’s gonna be important?

*Peter Todd:* Well, I’ll give you a
very specific answer, which is the things I’m working on with
client-side validation like Proof Marshall I think are critical to
moving this stuff to the next step. Getting past this narrative of all
we need some Ethereum chain, where everything’s in one place, which we
knew just doesn’t work.

I think smart contracts are actually really useful. But, they’re not
useful done in the way Ethereum people want to do them. It doesn’t work
technically. So, yes, this is kind of very narrow answer. But, this is
the stuff I’m directly working on. And, I think that’s a very fruitful
ground for making new and interesting things.

Beyond that, I mean, I’m sure the Lightning crowd, and so someone will
do great work in making payments better and so on. But, on the store of
value stuff, just not screwing up is enough to make that possible. So,
that’s kind of my answer there.

*Peter McCormack:* Great. This
was utterly fantastic. Thank you so much for coming on.

*Peter Todd:* Thank you.
