=== Satoshi Nakamoto - on lost coinst

****
* Source: https://bitcointalk.org/index.php?topic=198.0;all
* Author: Satoshi Nakamoto
* Date copied: 2022-05-25
****
////
This resource was created by going to the linked source, choose the
"print" option, copy the source from the "print page", paste the
content <table> element into a passthrough block using ++++, add
the .quote style, which is also copied from the print page source, to
btcphilosophy.css file.

I don't know how to make a style element "local" so that it doesn't
interfere with other contents styling. But if it should interfere, we
should rename the quote class used here to eg bitcointalkquote.

Converting this to asciidoctor would be too much hassle
////
++++
		<table width="90%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Dying bitcoins</b><br />
					Post by: <b>virtualcoin</b> on <b>June 21, 2010, 01:22:35 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Hello,<br /><br />if somebody&#039;s loosing his wallet (e.g. due to disk crash) he&#039;s not able to get back his coins, is he?<br />So every time a person looses coins, they&#039;re lost forever? So the bitcoin network will slowly shrink over time? (Because there will always be people who loose wallets!)<br /><br />TIA<br />virtualcoin<br /><br />edit: Forgot to mention the coins of users that are try out bitcoin and then never use it again.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>laszlo</b> on <b>June 21, 2010, 01:54:29 PM</b>
					<hr />
					<div style="margin: 0 5ex;">They are lost for good.&nbsp; Think of it like someone losing their wallet in the ocean.&nbsp; It seems like it would be a problem but it&#039;s really not that significant.&nbsp; People lose their gold jewelry all the time but it doesn&#039;t make much of a difference to the value of gold.<br /><br />I wonder though, is there a point where the difficulty of generating a new coinbase is so high that it would make more sense to try to recover keys for lost coins or steal other people&#039;s coins instead?&nbsp; The difficulty of that is really high so for now it makes a lot more sense to generate but I just wonder what the real figures are.. would that ever become more productive?&nbsp; Maybe Satoshi can address this..</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>virtualcoin</b> on <b>June 21, 2010, 02:33:31 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1640#msg1640">Quote from: laszlo on June 21, 2010, 01:54:29 PM</a></div><div class="quote">They are lost for good. &nbsp;Think of it like someone losing their wallet in the ocean. &nbsp;It seems like it would be a problem but it&#039;s really not that significant. &nbsp;People lose their gold jewelry all the time but it doesn&#039;t make much of a difference to the value of gold.</div><br />But loosing 1 bitcoin in the ocean of a maximum of 21.000.000 coins seems significant to me, so not comparable to gold and jewelry.<br />So only 21000 losses of 1000 coins can happen. That&#039;s not much!</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Gavin Andresen</b> on <b>June 21, 2010, 03:01:44 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1641#msg1641">Quote from: virtualcoin on June 21, 2010, 02:33:31 PM</a></div><div class="quote">But loosing 1 bitcoin in the ocean of a maximum of 21.000.000 coins seems significant to me, so not comparable to gold and jewelry.<br />So only 21000 losses of 1000 coins can happen. That&#039;s not much!<br /></div>But remember that each bitcoins can be divided into 100 million pieces, as needed.<br /><br />And the more valuable they become, the more careful people will be not to lose them.<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>virtualcoin</b> on <b>June 21, 2010, 03:54:43 PM</b>
					<hr />
					<div style="margin: 0 5ex;">So how am I able to transfer less than BC0.01 without getting the message &quot;error in amount&quot; from the bitcoin program?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>laszlo</b> on <b>June 21, 2010, 04:33:00 PM</b>
					<hr />
					<div style="margin: 0 5ex;">The current user interface doesn&#039;t support smaller than 0.01 increments but it is possible to support it in a future revision.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>satoshi</b> on <b>June 21, 2010, 05:48:26 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Lost coins only make everyone else&#039;s coins worth slightly more.&nbsp; Think of it as a donation to everyone.<br /><br /><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1640#msg1640">Quote from: laszlo on June 21, 2010, 01:54:29 PM</a></div><div class="quote">I wonder though, is there a point where the difficulty of generating a new coinbase is so high that it would make more sense to try to recover keys for lost coins or steal other people&#039;s coins instead?&nbsp; The difficulty of that is really high so for now it makes a lot more sense to generate but I just wonder what the real figures are.. would that ever become more productive?&nbsp; Maybe Satoshi can address this..<br /></div>Computers have to get about 2^200 times faster before that starts to be a problem.&nbsp; Someone with lots of compute power could make more money by generating than by trying to steal.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>summy</b> on <b>June 22, 2010, 11:51:25 AM</b>
					<hr />
					<div style="margin: 0 5ex;">Last but not least one can make tons of backups. Once could also setup a bank, even insurance could be made. You could also put your a wallet onto a media (cdrom, tape, whatever) and put it into a safe, like you would to it with money or gold. Then you can have a small wallet.<br /><br />In most regards bitcoin is just like any other currency. If you are stupid enough to not keep it save it&#039;s your fault. It&#039;s like walking on the beach with all your money. Simply don&#039;t do it!<br /><br />Maybe I could create a bank, but I&#039;d have to think about away to make myself trustworthy. ;)<br /><br />If you put your money onto a bank account you also have to trust them. If they mess up their system and nobody knows who was the owner of the money it&#039;s exactly the same. Inside the bank your money only exists in a virtual way. Most of the time (not always, because they invest your money) it is backed up by something physical, but if you loose the data to link the physical with the virtual stuff the system is completely messed up.<br /><br />To make it short: BitCoin is just money, so don&#039;t think of it as something too abstract. You can secure it, like every other money.<br /><br />In most situations it&#039;s easier. It isn&#039;t that easy to encrypt your money before you put it in your safe, is it?&nbsp; ;D</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>SmokeTooMuch</b> on <b>June 23, 2010, 07:41:14 PM</b>
					<hr />
					<div style="margin: 0 5ex;">last weak my hard drive crashed, good thing i backed up my wallet :)<br />as soon as i got my hard drive exchanged by western digital i will be back in the bitcoin system.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 18, 2012, 05:39:47 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Wouldn&#039;t it be good to modify the protocol, so any coins that weren&#039;t moved for 1000 days (for example) could be returned back into the system and mined again? We would get rid of some issues this way (lost coins, wasted space). Anyone who hoards bitcoins should just transfer the coins from wallet to wallet once a year.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>FreeMoney</b> on <b>September 18, 2012, 05:43:51 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Network size is not determined by the number of units. If it was we could have been ten times bigger now for the cost of one extra &quot;0&quot;!</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Kupsi</b> on <b>September 18, 2012, 05:54:37 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201451#msg1201451">Quote from: Come-from-Beyond on September 18, 2012, 05:39:47 PM</a></div><div class="quote">Wouldn&#039;t it be good to modify the protocol, so any coins that weren&#039;t moved for 1000 days (for example) could be returned back into the system and mined again? We would get rid of some issues this way (lost coins, wasted space). Anyone who hoards bitcoins should just transfer the coins from wallet to wallet once a year.<br /></div>So if I&#039;m going to jail for 10 years, my coins will be stolen from me? Bad idea.<br /><br />Two other threads on the topic from within the last month:<br /><br />https://bitcointalk.org/index.php?topic=104422.0 (https://bitcointalk.org/index.php?topic=104422.0)<br />https://bitcointalk.org/index.php?topic=109117.0 (https://bitcointalk.org/index.php?topic=109117.0)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>hazek</b> on <b>September 18, 2012, 06:15:22 PM</b>
					<hr />
					<div style="margin: 0 5ex;">Come-from-Beyond you do realize that you can take the Bitcoin source code, modify it how ever you like and start your own crypto currency that will follow the rules you want it to follow..<br /><br />If you aren&#039;t happy with Bitcoin the way it is, why not do that? We&#039;ll all be thankful and move to your currency if it turns out better than Bitcoin!</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Technomage</b> on <b>September 18, 2012, 06:21:40 PM</b>
					<hr />
					<div style="margin: 0 5ex;">I don&#039;t get where this argument comes from. I&#039;ve seen it many times. Making this argument requires a fatal flaw in logical thinking. Let me explain this in a simple way:<br /><br />People lose bitcoins -&gt; value of remaining bitcoins go up -&gt; average bitcoin user has less bitcoins -&gt; people lose less bitcoins on average -&gt; price still goes up -&gt; average bitcoin user has again less bitcoins -&gt; people lose less bitcoins on average.<br /><br />So in the long term this will only cause the price of bitcoins to go up a bit and for people to lose less bitcoins after that. Even in <b>a million years</b> we wouldn&#039;t reach 0 bitcoins and as you all should know, bitcoins can be divided to smaller pieces quite effectively.<br /><br />This argument is broken even without taking into account how educated people are in using Bitcoin. That is entirely irrelevant for countering this argument. Taking care of your bitcoins is a smart thing to do though, so I&#039;m all for it. :)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 18, 2012, 06:24:16 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201525#msg1201525">Quote from: hazek on September 18, 2012, 06:15:22 PM</a></div><div class="quote">Come-from-Beyond you do realize that you can take the Bitcoin source code, modify it how ever you like and start your own crypto currency that will follow the rules you want it to follow..<br /><br />If you aren&#039;t happy with Bitcoin the way it is, why not do that? We&#039;ll all be thankful and move to your currency if it turns out better than Bitcoin!<br /></div><br />Ok. I&#039;ll send u personal invitation. It&#039;s almost ready, just tuning minting algo. Should take 2-3 months.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 18, 2012, 06:27:08 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201485#msg1201485">Quote from: Kupsi on September 18, 2012, 05:54:37 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201451#msg1201451">Quote from: Come-from-Beyond on September 18, 2012, 05:39:47 PM</a></div><div class="quote">Wouldn&#039;t it be good to modify the protocol, so any coins that weren&#039;t moved for 1000 days (for example) could be returned back into the system and mined again? We would get rid of some issues this way (lost coins, wasted space). Anyone who hoards bitcoins should just transfer the coins from wallet to wallet once a year.<br /></div>So if I&#039;m going to jail for 10 years, my coins will be stolen from me? Bad idea.<br /><br />Two other threads on the topic from within the last month:<br /><br />https://bitcointalk.org/index.php?topic=104422.0 (https://bitcointalk.org/index.php?topic=104422.0)<br />https://bitcointalk.org/index.php?topic=109117.0 (https://bitcointalk.org/index.php?topic=109117.0)<br /></div><br />This thread is better. It was started quite earlier. :)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>DannyHamilton</b> on <b>September 18, 2012, 06:34:46 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201538#msg1201538">Quote from: Technomage on September 18, 2012, 06:21:40 PM</a></div><div class="quote">I don&#039;t get where this argument comes from. &lt;snip&gt;<br /></div><br />I&#039;m pretty sure it comes from over 2 years ago. <br /><br /><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1638#msg1638">Quote from: virtualcoin on June 21, 2010, 01:22:35 PM</a></div><div class="quote">Hello,<br />&lt;snip&gt;<br /></div><br />You know, back when Satoshi himself (or herself? or themselves?) was/were still participating in dicsussions.<br /><br /><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1647#msg1647">Quote from: satoshi on June 21, 2010, 05:48:26 PM</a></div><div class="quote">Lost coins only make everyone else&#039;s coins worth slightly more. &nbsp;Think of it as a donation to everyone.<br /></div></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Kupsi</b> on <b>September 18, 2012, 06:49:59 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201549#msg1201549">Quote from: Come-from-Beyond on September 18, 2012, 06:27:08 PM</a></div><div class="quote">This thread is better. It was started quite earlier. :)<br /></div>Yes, if you&#039;re not looking for updated information...</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Gabi</b> on <b>September 18, 2012, 07:47:54 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201451#msg1201451">Quote from: Come-from-Beyond on September 18, 2012, 05:39:47 PM</a></div><div class="quote">Wouldn&#039;t it be good to modify the protocol, so any coins that weren&#039;t moved for 1000 days (for example) could be returned back into the system and mined again? We would get rid of some issues this way (lost coins, wasted space). Anyone who hoards bitcoins should just transfer the coins from wallet to wallet once a year.<br /></div>No<br /><br />No it&#039;s not a good idea. It&#039;s a shitty idea<br /><br />In case it is not clear: NO<br /><br />Why the hell every week someone must come up with the same fail idea? </div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>justusranvier</b> on <b>September 18, 2012, 07:52:31 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201764#msg1201764">Quote from: Gabi on September 18, 2012, 07:47:54 PM</a></div><div class="quote">Why the hell every week someone must come up with the same fail idea?</div>Because the idea of not being able to steal other people&#039;s money fills them with great anxiety.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Gabi</b> on <b>September 18, 2012, 07:53:26 PM</b>
					<hr />
					<div style="margin: 0 5ex;">True that&nbsp; :D</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>nameface</b> on <b>September 18, 2012, 08:13:43 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1642#msg1642">Quote from: Gavin Andresen on June 21, 2010, 03:01:44 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1641#msg1641">Quote from: virtualcoin on June 21, 2010, 02:33:31 PM</a></div><div class="quote">But loosing 1 bitcoin in the ocean of a maximum of 21.000.000 coins seems significant to me, so not comparable to gold and jewelry.<br />So only 21000 losses of 1000 coins can happen. That&#039;s not much!<br /></div>But remember that each bitcoins can be divided into 100 million pieces, as needed.<br /><br />And the more valuable they become, the more careful people will be not to lose them.<br /><br /></div><br />AMEN!<br />By the time 1,000,000 coins have been lost, one coin might be worth $1,000,000 :) People don&#039;t tend to lose $1,000,000 worth of anything very often. There will forever be 20 million+ BTC in existence.<br />IMO if things continue to progress well it&#039;ll get harder and harder for people to lose coins as there will always be more and more technological innovation happening to prevents this. </div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 18, 2012, 08:38:46 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201764#msg1201764">Quote from: Gabi on September 18, 2012, 07:47:54 PM</a></div><div class="quote">Why the hell every week someone must come up with the same fail idea? <br /></div><br />It&#039;s not exactly the same. Most of my recent topics were made to find an answer for one important question. And I think I got it.<br /><br />It&#039;s impossible to have consensus regarding protocol changes in Bitcoin. It&#039;s a win-or-lose game, no anything in between allowed. So next-gen coin should have a protocol that could be adjusted by anyone without breaking the whole system.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>hazek</b> on <b>September 18, 2012, 09:00:47 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201918#msg1201918">Quote from: Come-from-Beyond on September 18, 2012, 08:38:46 PM</a></div><div class="quote">So next-gen coin should have a protocol that could be adjusted by anyone without breaking the whole system.<br /></div><br />We have that, it&#039;s called central banking and fiat currencies (FED + dollar, ECB + euro, and so on..)</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Desolator</b> on <b>September 19, 2012, 05:12:10 AM</b>
					<hr />
					<div style="margin: 0 5ex;">The subdivision thing cures this entire problem.&nbsp; Let&#039;s say 90% of all BTC are destroyed.&nbsp; Now the value of 0.1BTC is approximately the value that 1 BTC used to be, since there are only that many floating around.&nbsp; Life goes on.&nbsp; We&#039;re not in trouble of &quot;running out&quot; until like 99.999% of all BTC are destroyed because then there actually wouldn&#039;t be enough to go around.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 19, 2012, 05:17:46 AM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201969#msg1201969">Quote from: hazek on September 18, 2012, 09:00:47 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201918#msg1201918">Quote from: Come-from-Beyond on September 18, 2012, 08:38:46 PM</a></div><div class="quote">So next-gen coin should have a protocol that could be adjusted by anyone without breaking the whole system.<br /></div><br />We have that, it&#039;s called central banking and fiat currencies (FED + dollar, ECB + euro, and so on..)<br /></div><br />Really? I&#039;d like to increase emission of new dollar banknotes. What should I do?</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>kjj</b> on <b>September 19, 2012, 02:55:06 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1203062#msg1203062">Quote from: Come-from-Beyond on September 19, 2012, 05:17:46 AM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201969#msg1201969">Quote from: hazek on September 18, 2012, 09:00:47 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1201918#msg1201918">Quote from: Come-from-Beyond on September 18, 2012, 08:38:46 PM</a></div><div class="quote">So next-gen coin should have a protocol that could be adjusted by anyone without breaking the whole system.<br /></div><br />We have that, it&#039;s called central banking and fiat currencies (FED + dollar, ECB + euro, and so on..)<br /></div><br />Really? I&#039;d like to increase emission of new dollar banknotes. What should I do?<br /></div><br />Wait a few minutes.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Gabi</b> on <b>September 19, 2012, 02:58:31 PM</b>
					<hr />
					<div style="margin: 0 5ex;">+1 what hazek and kjj said</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 19, 2012, 03:23:11 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1204066#msg1204066">Quote from: Gabi on September 19, 2012, 02:58:31 PM</a></div><div class="quote">+1 what hazek and kjj said<br /></div><br />-1, coz no usefull info were provided.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>kjj</b> on <b>September 19, 2012, 03:28:24 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1204134#msg1204134">Quote from: Come-from-Beyond on September 19, 2012, 03:23:11 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1204066#msg1204066">Quote from: Gabi on September 19, 2012, 02:58:31 PM</a></div><div class="quote">+1 what hazek and kjj said<br /></div><br />-1, coz no usefull info were provided.<br /></div><br />You said you wanted to &quot;increase emission of new dollar banknotes&quot;.&nbsp; This is something that congress already does <b>to</b> you today.&nbsp; If you aren&#039;t happy with the current rate of emission, just wait a few minutes and it will be higher.</div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Phinnaeus Gage</b> on <b>September 19, 2012, 03:39:12 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1642#msg1642">Quote from: Gavin Andresen on June 21, 2010, 03:01:44 PM</a></div><div class="quote"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1641#msg1641">Quote from: virtualcoin on June 21, 2010, 02:33:31 PM</a></div><div class="quote">But loosing 1 bitcoin in the ocean of a maximum of 21.000.000 coins seems significant to me, so not comparable to gold and jewelry.<br />So only 21000 losses of 1000 coins can happen. That&#039;s not much!<br /></div>But remember that each bitcoins can be divided into 100 million pieces, as needed.<br /><br />And the more valuable they become, the more careful people will be not to lose them.<br /><br /></div><br />Exactly, for if all twenty-one million coins were lost, sans one, that one bitcoin can still be divisible even beyond the hundred millionth mark.<br /><br />~Bruno~<br /></div>
					<br />
					<hr size="2" width="100%" />
					Title: <b>Re: Dying bitcoins</b><br />
					Post by: <b>Come-from-Beyond</b> on <b>September 19, 2012, 04:31:41 PM</b>
					<hr />
					<div style="margin: 0 5ex;"><div class="quoteheader"><a href="https://bitcointalk.org/index.php?topic=198.msg1204144#msg1204144">Quote from: kjj on September 19, 2012, 03:28:24 PM</a></div><div class="quote">You said you wanted to &quot;increase emission of new dollar banknotes&quot;.&nbsp; This is something that congress already does <b>to</b> you today.&nbsp; If you aren&#039;t happy with the current rate of emission, just wait a few minutes and it will be higher.<br /></div><br />I expected other scenario. Without mediators. But thx anyway.</div>
					<br /><br />
					<div align="center" class="smalltext">
		<span class="smalltext" style="display: inline; visibility: visible; font-family: Verdana, Arial, sans-serif;"><a href="http://www.simplemachines.org/" title="Simple Machines Forum" target="_blank">Powered by SMF 1.1.19</a> | 
<a href="http://www.simplemachines.org/about/copyright.php" title="Free Forum Software" target="_blank">SMF &copy; 2006-2009, Simple Machines</a>
		</span></div>
				</td>
			</tr>
		</table>
++++
